### ISSUE TITLE
Enhancement: Provide 'Notifications' similar to 'Custom Apps'

### ISSUE THREAD

**Issue by Grothesk242** [klein0r/ioBroker.awtrix-light#10]
### The problem

Provide a Tab 'Notifications' similar to Custom Apps. 
So when a datapoint changes a notification appears on the display. 

### Version of nodejs

18.16.0

### Version of ioBroker js-controller

5.0.1-alpha.0-20230525-c580eb7e

### Version of Adapter

0.0.7 (git+ssh://git@github.com/klein0r/ioBroker.awtrix-light.git#9937b58abae9b025e0641d05ed6e34c2359700c5)

### Operating system running ioBroker

Debian 12 'Bookworm'

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
> So when a datapoint changes a notification appears on the display.

This is quite easy to implement with just 2 blocks in the javascript adapter.

**Comment by Grothesk242** [comment]
Sure, easy. 
For more complex skripts/blockies you would do it anyway. 
But very simple notifications would be 'at one place' in the Adapter settings.
