### ISSUE TITLE
History-App zeigt Graph mit 9 Pixeln höhe

### ISSUE THREAD

**Issue by heni1** [klein0r/ioBroker.awtrix-light#103]
### The problem

Die History App zeigt meinen Temperaturgraph mit 9 Pixeln höhe. Die unterste "Linie" wird herausgeschoben. Ich sehe Sie nur kurz in der Übergangsanimation.

The history app shows my temperature graph with a height of 9 pixels. The bottom "line" is pushed out. I only see it briefly in the transition animation.

### Version of nodejs

v18.18.2 

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

v0.10.1

### Version of awtrix-light firmware

AWTRIX Light 0.90

### Operating system running ioBroker

Linux (Docker)

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

Uploading 9 Pixel History-App.mp4…

**Comment by heni1** [comment]
Uploading 9 Pixel History-App.mp4…

**Comment by klein0r** [comment]
Ohne Debug-Log kann ich hier nix machen. Kam nichts mehr nach.
