### ISSUE TITLE
LUX Sensor value

### ISSUE THREAD

**Issue by Rushmed** [klein0r/ioBroker.awtrix-light#104]
### The problem

Hi,
compared to other LDR sensors in my house the lux value shown in the awtrix adapter objects is way too low (5...100 times too low).
Where does this value come from? Cant find the request command for Awtrix-light. Is it sure given in lux or maybe percent?
Maybe there are some other mathematics in background.
Auto brightness is working well. But I cant use this sensor for other automations because in dimm light situations its very fast at 0 or zero even if theres much light in the room.

Tested this on two Ulanzis.

### Version of nodejs

v18.19.0

### Version of ioBroker js-controller

 5.0.17

### Version of Adapter

v0.10.2

### Version of awtrix-light firmware

0.91

### Operating system running ioBroker

Linux Bookworm

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
> Where does this value come from?

From awtrix-light. The value is requested via http and the value will be written to the state (without any modification). This is not an adapter issue.

**Comment by Rushmed** [comment]
Ok I asked Blueforcer. 
Pls find his answer here: https://github.com/Blueforcer/awtrix-light/issues/433#issuecomment-1859134533
The given value of the light sensor in the adapter is NOT lux. Pls fix unit and name.
Thanks in further.
