### ISSUE TITLE
Visibility-Object for custom apps

### ISSUE THREAD

**Issue by Dabu5** [klein0r/ioBroker.awtrix-light#11]
### The problem

The visibility of built-in apps can be controlled via an object. This feature is missing for custom apps

### Version of nodejs

16.19.0

### Version of ioBroker js-controller

4.0.19

### Version of Adapter

0.0.8

### Operating system running ioBroker

Unraid Docker

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
> This feature is missing for custom apps

It's not missing. "Invisible" just doesn't exist. Setting an app to invisible means: Delete it. And a new state change would re-create it. So it makes no sense to provide that object.
