### ISSUE TITLE
Feature Request: Add information about IPAddress as an object data point.

### ISSUE THREAD

**Issue by SteevieBDE** [klein0r/ioBroker.awtrix-light#111]
### The problem

Moin.
Awtrix Light IP address (received from DHCPD)  transmit its IP address as an object to IOBroker.
It would be helpful in some occasions to get this information from a data point I m (maybe in meta or info) to quickly identify the IP of the light without searching the "FritzBox's" IP leases objects.

### Version of nodejs

v18.17.1

### Version of ioBroker js-controller

5.0.16

### Version of Adapter

0.10.0

### Version of awtrix-light firmware

0.94

### Operating system running ioBroker

Ubuntu on Proxmox CT

### Checklist of files to include below

- [ ] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
MQTT is not supported by this adapter?!

**Comment by SteevieBDE** [comment]
Yes Matthias, you are absolutely correct - my mistake.
But, it would be very helpful to have the IP address information in the Awtrix-light objects e.g. in info or meta section.
Thanks for quick response. 
I will rephrase the feature request accordingly
And , it’s Notnagel bug. Can I delete the BUG tag somehow?

**Comment by klein0r** [comment]
> But, it would be very helpful to have the IP address information in the Awtrix-light objects e.g. in info or meta section.

Just use `device.ipAddress` 😄

**Comment by SteevieBDE** [comment]
> Just use `device.ipAddress` 😄

...would love to, but I don't have "device.ipAddress" in Objects

![Bildschirmfoto 2024-01-14 um 10 30 59](https://github.com/klein0r/ioBroker.awtrix-light/assets/33467113/97889f53-1619-4bca-b24a-93f7e86bb4e6)

**Comment by klein0r** [comment]
Has been added in

https://github.com/klein0r/ioBroker.awtrix-light/blob/a7fa2acb6b2cd58d1fc14b00207131f787e54bbe/README.md?plain=1#L53-L57

Please read all information when creating new issues. Like

> Ensure that you use the latest beta version (not the current stable version): 0.11.0

**Comment by SteevieBDE** [comment]
Thx for your patience. 🥇 
As I usually don't use "beta" versions as far as possible, I'm happy to wait until it is in the stable train...
Again, thanks a lot - its my 1st GitHub submission ever - starting my "learning curve" in commenting in a reasonable manner...
