### ISSUE TITLE
Enhancement / Icons changeable by ioBroker-object

### ISSUE THREAD

**Issue by Dabu5** [klein0r/ioBroker.awtrix-light#12]
### The problem

Can the icon of a custom app be changed via an object? (comparable to the text) e.g. a Userobject with the icon id as the content

### Version of nodejs

16.19.0

### Version of ioBroker js-controller

4.0.19

### Version of Adapter

0.0.8

### Operating system running ioBroker

Docker

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
The question is: How many options do you want? 😄 Apps support several options (see https://blueforcer.github.io/awtrix-light/#/api?id=json-properties). You can create a feature request for all of them (and to change the icon via state). After that, nobody will understand all options and features.

At the moment I want to keep everything as simple as possible.
