### ISSUE TITLE
Objekte Readonly - Apps/Visible

### ISSUE THREAD

**Issue by reihd** [klein0r/ioBroker.awtrix-light#120]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Version of awtrix-light firmware

0.94

### The problem

ich habe mir die Version 0.15.0 installiert. Danach konnte ich die Objekte unter Apps nicht mehr steuern, speziell hier Visible. Die sind auf einmal Readonly. Ist das gewollt?

### Version of nodejs

v18.18.2

### Version of ioBroker js-controller

5.0.19

### Version of adapter

0.15.0

**Comment by klein0r** [comment]
Das sollte eigentlich nur bei "kopierten" App-Einstellungen passieren.

https://github.com/klein0r/ioBroker.awtrix-light/blob/ab63051a99710af5a58a5d8f543d65407c20ab8d/docs/de/README.md?plain=1#L76

**Comment by reihd** [comment]
das müsste ich testen. Aber warum? Ich habe tatsächlich 2 Geräte und habe die Einstellungen auch von 0 auf 1 kopiert. Aber dennoch möchte ich die Visible Einstellungen unterschiedlich setzen, da die Geräte ja nicht in einem Raum sind. Also müsste ich beide Geräte extra Parametrieren? Dann sollte es ja passen

**Comment by klein0r** [comment]
> Aber warum?

Weil das hier eine Anforderung war: https://github.com/klein0r/ioBroker.awtrix-light/issues/74

Am Ende möchte ja wahrscheinlich (wenn man die App-Einstellungen kopiert) ja auch 1:1 das gleiche darstellen. So war zumindest mal die Idee des Ganzen. Mit den Experten-Apps kann man über Zustände ja auch den Text selbst in einen State schreiben, oder die Farbe. Da fand ich schon etwas komisch, dass man die Apps zwar kopieren kann, aber die Inhalte dann trotzdem in alle States selbst schreiben muss. Das habe ich mit der Version korrigiert. "Visible" dann auf das gleiche Verhalten anzupassen, war für mich erstmal nur logisch, damit sich alles gleich verhält.

Aber klar, wenn Du keine Einstellungen kopierst, kannst Du visible wieder separat steuern.

**Comment by reihd** [comment]
ja, dann ist es halt so. Der Vorteil bei deinem Adapter ist, ich kann die Einstellungen sichern und wiederherstellen, dass macht dann nicht so viel Arbeit. Vielen Dank für die Antworten.

**Comment by klein0r** [comment]
> ich kann die Einstellungen sichern und wiederherstellen

Das klappt aber bei jeder Instanz und ist ein Feature vom Admin 👍
