### ISSUE TITLE
Feature Request: Ändere App Icon auf Basis des Wertes

### ISSUE THREAD

**Issue by pellenbeck** [klein0r/ioBroker.awtrix-light#122]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Version of awtrix-light firmware

awtrix_3d13a8

### The problem

Am Beispiel der Anzeige des aktuellen Strombezugs eines Hauses:

Sofern der genutzte Wert positiv ist (=Bezug aus Netz), soll ein rotes Icon verwendet werden; wenn der Wert negativ ist (=Einspeisung), soll ein grünes Icon verwendet werden.

Workaround wäre es in zwei verschiedenen Apps umzusetzen, die jeweils aktiviert/deaktiviert werden.

### Version of nodejs

v18.19.0

### Version of ioBroker js-controller

v9.1.1

### Version of adapter

v0.13.1

**Comment by klein0r** [comment]
Das geht doch schon mit den Schwellwerten - oder was verstehe ich nicht an der Anforderung?

**Comment by pellenbeck** [comment]
Im Prinzip ist es das, ja. Allerdings wird der Wert dann mit Vorzeichen ausgegeben, was es nicht bräuchte, da das Icon dies schon idiziert.

**Comment by klein0r** [comment]
Naja wie soll die Konfiguration dafür aussehen? Zusätzlich einen Haken, dass immer nur positive Werte angezeigt werden sollen? Da sieht ja niemand mehr durch. Am besten mit einer Experten-App selbst umsetzen und das Icon dann dynamisch anpassen. Zwei Apps (welche immer ein- und ausgeblendet werden) ist jedenfalls der falsche Weg.

**Comment by pellenbeck** [comment]
Ja, da gebe ich dir recht. Als Frontend wäre das sehr überladen.

Wie und wo kann ich denn auf das Icon der Apps zugreifen bzw. dieses setzen?
Als Datenpunkt/Objekt gibt es das nicht.
