### ISSUE TITLE
[Bug]: Verbindung Adapter zur Uhr funktioniert nicht.

### ISSUE THREAD

**Issue by Freakinstar** [klein0r/ioBroker.awtrix-light#126]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Version of awtrix-light firmware

0.96

### The problem

Hallo,

ich habe ein Problem mit der Verbindung zwischen Adapter und Uhr, Der Adapter verbindet nicht mit der Uhr und es werden auch keine Apps angezeigt.  Die Weboberfläche der Uhr ist unter der hinterlegten Adresse im Browser erreichbar.

### iobroker.current.log (in debug mode!)

<html>
<body>

host.raspberrypi | 2024-04-03 20:13:41.634 | error | instance system.adapter.awtrix-light.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.raspberrypi | 2024-04-03 20:13:41.634 | error | Caught by controller[0]: at node:internal/main/run_main_module:22:47
host.raspberrypi | 2024-04-03 20:13:41.634 | error | Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
host.raspberrypi | 2024-04-03 20:13:41.634 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:911:12)
host.raspberrypi | 2024-04-03 20:13:41.634 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1076:32)
host.raspberrypi | 2024-04-03 20:13:41.633 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
host.raspberrypi | 2024-04-03 20:13:41.633 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1198:14)
host.raspberrypi | 2024-04-03 20:13:41.633 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.awtrix-light/build/main.js:41:33)
host.raspberrypi | 2024-04-03 20:13:41.633 | error | Caught by controller[0]: TypeError: Class extends value #<Object> is not a constructor or null
host.raspberrypi | 2024-04-03 20:13:41.633 | error | Caught by controller[0]: ^
host.raspberrypi | 2024-04-03 20:13:41.633 | error | Caught by controller[0]: class AwtrixLight extends utils.Adapter {
host.raspberrypi | 2024-04-03 20:13:41.632 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.awtrix-light/build/main.js:41

</body>
</html>

### Version of nodejs

16.20.2

### Version of ioBroker js-controller

 5.0.19

### Version of adapter

 0.16.0

**Comment by klein0r** [comment]
> ### Version of nodejs
> 16.20.2

Version 16.x is EOL and no longer supported: https://endoflife.date/nodejs

**Comment by Freakinstar** [comment]
Update auf Nodejs 18.20.1
Der Fehler bleibt identisch

```
<html>
<body>
<!--StartFragment-->
host.raspberrypi | 2024-04-03 20:43:44.465 | error | instance system.adapter.awtrix-light.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.raspberrypi | 2024-04-03 20:43:44.465 | error | Caught by controller[0]: Node.js v18.20.1
host.raspberrypi | 2024-04-03 20:43:44.465 | error | Caught by controller[0]: at node:internal/main/run_main_module:28:49
host.raspberrypi | 2024-04-03 20:43:44.465 | error | Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
host.raspberrypi | 2024-04-03 20:43:44.464 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:1019:12)
host.raspberrypi | 2024-04-03 20:43:44.464 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1203:32)
host.raspberrypi | 2024-04-03 20:43:44.464 | error | Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
host.raspberrypi | 2024-04-03 20:43:44.464 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1364:14)
host.raspberrypi | 2024-04-03 20:43:44.464 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.awtrix-light/build/main.js:41:33)
host.raspberrypi | 2024-04-03 20:43:44.464 | error | Caught by controller[0]: TypeError: Class extends value #<Object> is not a constructor or null
host.raspberrypi | 2024-04-03 20:43:44.463 | error | Caught by controller[0]: ^
host.raspberrypi | 2024-04-03 20:43:44.463 | error | Caught by controller[0]: class AwtrixLight extends utils.Adapter {
host.raspberrypi | 2024-04-03 20:43:44.463 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.awtrix-light/build/main.js:41

<!--EndFragment-->
</body>
</html>
```

**Comment by Freakinstar** [comment]
Reinstalled the adapter.
