### ISSUE TITLE
[Bug]:  Error

### ISSUE THREAD

**Issue by AdamK-DE** [klein0r/ioBroker.awtrix-light#127]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Version of awtrix-light firmware

123

### The problem

der fehler trat wieder auf. 
alle x wochen mal:

javascript.0 | 2024-04-23 12:26:00.775 | error | Error:  read ECONNRESET     at Function.AxiosError.from  (/opt/iobroker/node_modules/iobroker.javascript/node_modules/axios/lib/core/AxiosError.js:89:14)     at RedirectableRequest.handleRequestError  (/opt/iobroker/node_modules/iobroker.javascript/node_modules/axios/lib/adapters/http.js:610:25)     at RedirectableRequest.emit (node:events:517:28)     at RedirectableRequest.emit (node:domain:489:12)     at ClientRequest.eventHandlers.<computed>  (/opt/iobroker/node_modules/follow-redirects/index.js:38:24)     at ClientRequest.emit (node:events:529:35)     at ClientRequest.emit (node:domain:489:12)     at Socket.socketErrorListener (node:_http_client:501:9)     at Socket.emit (node:events:517:28)     at Socket.emit (node:domain:489:12)     at emitErrorNT (node:internal/streams/destroy:151:8)     at emitErrorCloseNT (node:internal/streams/destroy:116:3)     at processTicksAndRejections  (node:internal/process/task_queues:82:21)
-- | -- | -- | --
javascript.0 | 2024-04-23 12:26:00.775 | error | Error: read ECONNRESET
javascript.0 | 2024-04-23 12:26:00.775 | error | An error happened which is most likely from one of your scripts, but the originating script could not be detected.

**ps: gesendet per blockly/JS:

const axios = require('axios');
var API_SERVER = 'http://'+ ip + '/json/state';

axios.post(API_SERVER, inhalt, {
  headers: {
    'Content-Type': 'application/json'
  }
});**

### Version of nodejs

123

### Version of ioBroker js-controller

123

### Version of adapter

123

**Comment by klein0r** [comment]
Keine Ahnung was das mit awtrix-light zu tun hat?
