### ISSUE TITLE
Feature Request: Option "hold" im blockly Modul

### ISSUE THREAD

**Issue by marlan99** [klein0r/ioBroker.awtrix-light#13]
### The problem

Feature:
Könnte man bitte die Option "hold" im blockly Modul verfügbar machen?

### Version of nodejs

16.19.1

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.0.8

### Operating system running ioBroker

Raspberry

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

Wollte es als Feature Request erstellen. Habe irgendwie nur "bug" auswählen können

**Comment by marlan99** [comment]
Als Idee: Eine Option wäre evtl. "hold" zu aktivieren, wenn man die Dauer auf 0 setzt ?

Sonst gerne dieses feature request einfach schliessen

**Comment by klein0r** [comment]
> Als Idee: Eine Option wäre evtl. "hold" zu aktivieren, wenn man die Dauer auf 0 setzt ?

Aktuell wird 1:1 das an Optionen durchgereicht, was man als JSON reingibt. Möchte da ungern etwas Magie zwischen packen, welche dann Optionen austauscht (z.B. duration durch hold ersetzt).

Du kannst das ja ohne Blockly direkt im JavaScript mit sendTo alles selbst umsetzen mit allen verfügbaren Optionen.

**Comment by haahne** [comment]
Fände diese "Hold" Funktion auch ganz sinnvoll.

**Comment by klein0r** [comment]
Added in >= 0.13.1
