### ISSUE TITLE
[Bug]: fehler beim kopieren der apps 0.1 -> .1

### ISSUE THREAD

**Issue by AdamK-DE** [klein0r/ioBroker.awtrix-light#130]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Version of awtrix-light firmware

1

### The problem

bug beim kopieren der apps aus .0 für .1:

apps/visible true/false wird kopiert aber das activate nicht! :( 

mein ganzes system baut darauf auf. keine apps an aber sobald jemand an der tür ist etc springt die "haustür" per visible: true und activate:ture an (mit icon) und wird glaub 20sec lang angezeigt mit wechsel alle 60sec aber das wird nach 30sec wieder auf visible:false gesetzt etc.........

unter objekte kann ich auch activate bei .1 von hand triggern aber visible nicht da kopiert..

so macht das kopieren hier null sinn :(
baust du das um? ansonsten passe ich alle blocklys an und trigger beide uhren an. dann ist kopieren aber müll. gibt chaos.. dann wärs schlauer alle apps von hand zu kopieren.. hm

### Version of nodejs

123

### Version of ioBroker js-controller

32323

### Version of adapter

32323

**Comment by klein0r** [comment]
Ich kann mittlerweile an der Wortwahl und am Satzbau erkennen dass Du das geschrieben hast 😄

**Comment by klein0r** [comment]
> ### Version of nodejs
> 123
> 
> ### Version of ioBroker js-controller
> 32323
> 
> ### Version of adapter
> 32323

Warum ist es eigentlich so schwer die Infos richtig auszufüllen?

**Comment by AdamK-DE** [comment]
die infos sind doch irrelevant ;) .........

baust du um?? 
hab die blocklys schon umgebaut... 
verdammt, die uhr ist so geil .. :) hole ne dritte.. 
laß, ich baus hier um.. evtl gar nicht so verkehrt das da snicht zusammen geschalten wird.. ich trenne die 3 und kopier die apps von hand dann kann ich später individuel drauf eingehen... habe z.b. den alexa timer darpber laufen, genial! alle 60 sec wird per app der timer für 10 sec eingeblendet.. trennt man das dann kann ich die 3te uhr für die küche dauerhaft auf dem timer lassen... hat vorteile..  und im büro bei uhr2 mehr infos anzeigen lassen als im wohnzimmer..

passt! :) 

und wann kommt der text mit ICONS im text??? :) haben willllllllll! :P glaub bei HA ist das mit drinn und kann awtrix ja... bei sowas wie "alexa wie sind die temperaturen" scrollt das hier alles auch als text durch. da ohne icon da das zu viel platz links wegnimmt. bei anderen sachen habe ichs drinn wenn kurz.. naja.. 


ps: wieso startet der text immer mittig? kann man da nichts dran ändern? will das er von rechts nach links rein scrollt wie sich das gehört. 
der poppt mittig auf und scrollt immer von da nahc links weg.. das sieht doch nach nichts aus. vorallem ohne icon.. mit passt das aber.

**Comment by AdamK-DE** [comment]
> > ### Version of nodejs

 v18.19.0
 
> > ### Version of ioBroker js-controller

 5.0.17
 ich verweigere das update :P
 da kammen viel zu viele.. sowas alle 6mon mal reicht..  lieber alle 2 jahre mal..
 

> > ### Version of adapter

starting. Version 0.16.0
> > 32323

**Comment by AdamK-DE** [comment]
verdammt wo ist dein paypal donate?????????????????
nix in der instanz..

**Comment by klein0r** [comment]
> starting. Version 0.16.0
> 
> und was bringen dir diese infos nun? nixxxxxxx :P

Zumindest weiß ich, dass Du eine ältere Adapter-Version verwendest und dass es in 1.0.1 einige Fixes genau zu diesem Thema gab.

**Comment by AdamK-DE** [comment]
hätte übrigens so lust das alles in axios zu machen. ohne den adapter in blockly :P oder selbst den adapter.. aber mir fehlt die zeit :(

**Comment by AdamK-DE** [comment]
naja.................
auf beta res:

Installierte Instanzen:
2
Verfügbare Version:
0.10.2
Installierte Version:
0.16.0

jaja mache es per hier aber hasse das..

**Comment by AdamK-DE** [comment]
nach update per NPM:

Awtrix 3 (Awtrix Light)
Installierte Instanzen:
2
Verfügbare Version:
0.16.0
Installierte Version:
1.0.1


nun wird aktivieren auf wahr gesetzt. aber so verzögert.. unbrauchbar :( ... 
*mess*
hööö.. nun gehts wieder nicht.. so war das mit dem ersten deiner adapter auch. das erste mal ging, danach tod ;) der setzt dieses activate nicht mehr auf true.. die apps bleiben visible:true aber der activate trigger kommt nicht..

**Comment by klein0r** [comment]
> apps/visible true/false wird kopiert aber das activate nicht! :(

Gerade nochmal geschaut. `activate` wird nicht auf die anderen Instanzen übertragen, richtig. Der Grund dafür ist, dass man ja ggf. auf einem Gerät eine App aktivieren möchte, sobald man den Raum betritt oder eine andere Aktion eintritt.

Und die Native-Apps (Time, Date, Temperature, Humidity, Battery) kann man ja auch aktivieren. Nur dass diese ggf. gar nicht auf den anderen Geräten aktiv sind.

Werde das also als weitere Option einfügen (ob man activate auch spiegeln möchte).

**Comment by AdamK-DE** [comment]
alles klar. passt :) 

für die nächste PRO version:

bau was ein zum brightness AUTO lassen aber "abfedern".. 
hier scheint TV ambilight auf die uhr im wohnzimmer. die geht mit auto alle 1-2 sec heller/dunkler. supper nervig aber klar da der esp32 die lux recht häufig misst und sendet. ich habe auto.bright auf false und setze das per blockly nur verzögert auf true für 5 sec dann wieder false. glaube ab lux abweichung 10 oder so erst.. dann flackert das ding nicht dauernd rum aber stellkt trotzdem auf größere helligkeitsunterschiede um... ich triggere da auf die lux oder wie das da heissst.. und nach apps starts macht er das auch immer kurz auf auto.. aber generell muss das hier false sein... 

die 2te, besser plaziert (wird nicht angestrahlt), steht auf auto. da passt das so gut.

**Comment by AdamK-DE** [comment]
was soll denn dieser sponsor mist hier? nur exakt 1 zahlungsmöglichkeit. arm.. 
paypal donate?? adam@kopacz.de

**Comment by AdamK-DE** [comment]
PS: habe alle icons von hand gesucht aus der instanz->apps und auf die 2te uhr geladen.. 

evtl als PLUS: beim kopieren der instanz bzw deren apps könnte der adapter das schons elbst erledigen ;) ode rmelden daas man es sicher muss?!

**Comment by klein0r** [comment]
> evtl als PLUS: beim kopieren der instanz bzw deren apps könnte der adapter das schons elbst erledigen

Dafür gibt es keine dokumentierte Schnittstelle. Leider.

Wäre ein Feature-Request in awtrix3

**Comment by klein0r** [comment]
> nun wird aktivieren auf wahr gesetzt. aber so verzögert.. unbrauchbar :( ...

Das ist übrigens ein write-only state (`common.read: false`) mit der rolle `button`. `activate` wird dir niemals einen Status geben, sondern ist nur zum schreiben gedacht (und auch nur den Wert `true` schreiben). ioBroker Grundlagen anschauen.

Und: Expertenmodus ausmachen, den brauchst Du einfach nie.

**Comment by klein0r** [comment]
Fixed in 1.1.0

**Comment by AdamK-DE** [comment]
"pushIcon": 2
bei den custom apps ist das was fehlt.
baust du das ein? bei allen apps zum ICOn dazu:

0: default, icon steht. text scrollt
2: icon scrollt mit text weg

rest: keine ahnung! ;))))

fand das eben in : 
https://www.youtube.com/watch?v=AkCocqeyH_U

**Comment by AdamK-DE** [comment]
text Invertiert wäre evtl noch gut?

{
"text": "Invertiert",
"color": "#000000",
"background": "#ffffff"
}

--------------------------
FARBVERLAUF AUF TEXT fehlt auch noch! ;) du hast nur den rainbow da. hier geht farbe VON zu BIS :):

{
"text": "Verlauf",
"gradient": [
  "#BDD4E7",
  "#2EC4B6"
  ]
  }

**Comment by AdamK-DE** [comment]
progress bar?? wooo ist sie? ;) GEIL!!! :)

damit ginge auch ein effekt unter laufenden text.. die könnte man wild zappeln lassen ;)
AWTRIX3 hat wohl einiges neues?! :)

baust du alles ein? :P

**Comment by klein0r** [comment]
> baust du alles ein? :P

Kann Dir gern ein Angebot für Deine Wünsche schicken. Alleine an diesem Issue hier saß ich gut 3 Stunden (weil dafür recht viel umstrukturiert werden musste, da es nie so geplant war).

**Comment by AdamK-DE** [comment]
oder.. ich mache das in mqtt oder http post einfach selbst ;) doch wieder blockly.. dann habe ich aber alles..

die API ist ja super simpel..  ne app über der es schneit oder regnet stand eben in 3min.. 
die progress bar (echt nett für waschmaschinen status etc) in 30 sec...

denke bei dir wird das html frontend dafür die meiste zeit brauchen..

const axios = require('axios');
var API_SERVER = 'http://'+ ip + '/api/settings';

axios.post(API_SERVER, inhalt, {
  headers: {
    'Content-Type': 'application/json'
  }
});


inhalt: {   "OVERLAY": "snow" }
ip: ....


https://blueforcer.github.io/awtrix3/#/api

**Comment by klein0r** [comment]
Axios und die API kenne ich in und auswendig, danke 😄 

Mach doch einen PR für den Adapter hier?
Du kannst ja programmieren wie es aussieht.

**Comment by AdamK-DE** [comment]
was ist ein PR?
bei mir ist das 25j her..  linux und unter win95 dann C++ ;) und pascal!! haha ;) 
und bei sowas ist die meiste arbeit ja das intergrieren ins hübche user klicki-bunti interface ;) bei mir hätte da jede app 2 seiten mit allem an möglichkeiten und inkl vorschau bilder zum ergebniss.. plus am ende ne preview die schnell was an awtrix schonmal ohne speichern rausschickt.  man kann nichts testen im apps dialog ding.. 

appropos: reload bei awtrix.1 hängt als. muss mal mit der neusten NPM sehen. mit der davor musste ich .1 oft von hand pausieren (nach app änderungen) und selbst starten. auto reload nach .0 lief langsamer als von hand aber klappte oft nicht. ioB logo kam bei .1 nicht.. gewöhnte mir an nach .0: speichern sofort .1 zu pausieren udn sobald .0 grün wird .1 wiede rzu starten und so klappte das app-update immer...

**Comment by AdamK-DE** [comment]
spielte übrigens mal herum.
NAJA.. das mit dem "icon scrollt mit text raus" müsstest du echt einbauen, da sist genial für längere info texte. 

aber der rest ist spielkram... snow/stormy etc braucht kein mensch.. progressbar.. hm kann man sich eigentlich auch per icon basteln wenn man das will in 10 schritten etc.. irgendeine andere bar bekam ich auf die schnelle gar nicht ans laufen.. 

eine "night rider" bar mit linie ganz unten die eh immer frei bleibt wäre cool für info texte etc.. könnte man evtl per overlay app auch so hinbekommen.. overlay in 32x1 px und dort ne linie malen etc..

**Comment by AdamK-DE** [comment]
btw, überall wird auf diese lumilancedingens seite wegen den icons verwiesen.. hat nem bug seit wochen. unten rechts ist immer ein pixel falsch bei allen anim gifs die man da erstellt.. fand erst vor 2 tagen heraus das man da genauso direkt GIF anims auf den esp laden kann. aus photoshop.. UND du hast mitgedacht wies scheint :) icon nr = keine nummer sondern string DP.. auf dem esp kann man wohl auch furz.gif draufladen..

![60411(1)](https://github.com/klein0r/ioBroker.awtrix-light/assets/127183545/c7f2f13f-e4f7-47e1-b973-b1f331860b68)
![60412(1)](https://github.com/klein0r/ioBroker.awtrix-light/assets/127183545/16f24863-86fa-47fa-a65f-a68582e27ed6)
