### ISSUE TITLE
[Bug]:  namen falsch

### ISSUE THREAD

**Issue by AdamK-DE** [klein0r/ioBroker.awtrix-light#131]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Version of awtrix-light firmware

1

### The problem

die namen der objekte der expert apps sind falsch:

duration = Symbol
icon = Symbol

zudem: hatte netzwerk-probleme. awtrix meldet da teils timeouts udn teils err 500 im log.. 3000ms oder so?
prob: das deaktiviert die apps dann aber anscheinend gar nicht mehr. auch 10min später nicht. evtl hier die sende-versuche hoch setzen? nach 2min war alles wieder ok aber wurden trotzdem nicht deaktiviert.

### Version of nodejs

1

### Version of ioBroker js-controller

2

### Version of adapter

3

**Comment by klein0r** [comment]
no debug log attached

**Comment by AdamK-DE** [comment]
jepp, behoben. sehe das aktivieren der apps nun auch beim kopieren :) thanx! 


admin.0 | 2024-05-16 13:06:10.497 | warn | awtrix-light  has an invalid jsonConfig:  [{"instancePath":"/items/_customApps/items/customApps/items/16/data","schemaPath":"#/items/allOf/2/then/properties/data/type","keyword":"type","params":{"type":"object"},"message":"must  be  object"},{"instancePath":"/items/_customApps/items/customApps","schemaPath":"#/patternProperties/%5E.%2B/allOf/42/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must  match \"then\"  schema"},{"instancePath":"/items/_customApps","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must  match \"then\"  schema"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must  match \"then\" schema"}]
-- | -- | -- | --
admin.0 | 2024-05-16 13:05:13.768 | warn | awtrix-light  has an invalid jsonConfig:  [{"instancePath":"/items/_customApps/items/customApps/items/16/data","schemaPath":"#/items/allOf/2/then/properties/data/type","keyword":"type","params":{"type":"object"},"message":"must  be  object"},{"instancePath":"/items/_customApps/items/customApps","schemaPath":"#/patternProperties/%5E.%2B/allOf/42/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must  match \"then\"  schema"},{"instancePath":"/items/_customApps","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must  match \"then\"  schema"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must  match \"then\" schema"}]
awtrix-light.1 | 2024-05-16 13:04:57.567 | info | Using settings of other instance: awtrix-light.0
awtrix-light.1 | 2024-05-16 13:04:57.565 | info | Starting - connecting to http://192.168.178.111:80/
awtrix-light.0 | 2024-05-16 13:04:57.530 | info | Starting - connecting to http://192.168.178.113:80/
awtrix-light.1 | 2024-05-16 13:04:57.486 | info | starting. Version 1.2.0 in /opt/iobroker/node_modules/iobroker.awtrix-light, node: v18.19.0, js-controller: 5.0.17

**Comment by klein0r** [comment]
@AdamK-DE Ich musste übrigens mal wieder selbst schauen, was Du mit den Beschreibungen hier meinst. Bitte gib Dir mehr Mühe bei den Fehler-Reports... und nur 1 Thema pro Issue. Ich gebe mir hier ja auch alle Mühe und investiere sehr viel Zeit in die Adapter-Pflege.

**Comment by AdamK-DE** [comment]
ja, sorry.. 

prob: du machst das hier immer so schnell zu! man findet es dann gar nicht mehr.. nehme dann irgendein issue aus ner email etc und poste halt immer da noch was ;)

-------------------------

... das progress ding eben entdeckt! wow! klappt beim testen 1A ABER irgendwo haben die expert apps noch den wurm drinn. beim init also ohne werte bleiben die uhren als schwarz..  restart der instanz reicht dann aber..

stelle hier gerade eben um. nun getrennt die 2 uhren. ist besser so im handling. diverse apps kopiert und teils eigene pro uhr. 

------------

bastle gerade mit expert ne wetter app inkl individuellen icon je nach wetter gerade.. mal sehen.. dazu muss man ja erstmal 20 bildchen auf 8x8 bringen unter beachtung dieser codes dafür von weatherunderground.... 

per blockly aber expert app individuel setzen klappt 1A! :)

**Comment by klein0r** [comment]
> prob: du machst das hier immer so schnell zu!

Weil die abgefragten Infos ja im Issue nicht enthalten sind und die Fehlerbeschreibung unverständlich ist. Ein Debug-Log fehlt auch. Daher der Hinweis

> Otherwise this issue will be closed.
