### ISSUE TITLE
[Enhancement]: App Anzeigedauer über Datenpunkt steuern

### ISSUE THREAD

**Issue by juergiboy** [klein0r/ioBroker.awtrix-light#138]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Version of awtrix-light firmware

0.96

### The problem

Da ich, abhängig von den jeweiligen Umständen, gerne die Anzeigedauer der Apps anpassen möchte, würde ich mir wünschen diese auch über einen Datenpunkt per Skript steuern zu können.
Die Anpassung in der Instanz ist ja nicht über ein Skript möglich.
Die API gibt das ja eigentlich her (duration), daher sollte das doch umsetzbar sein?

### Version of nodejs

v18.20.2

### Version of ioBroker js-controller

6.0.1

### Version of adapter

1.2.1

**Comment by klein0r** [comment]
> Die Anpassung in der Instanz ist ja nicht über ein Skript möglich.

Geht schon, aber wäre nicht schön das Instanz-Objekt zu bearbeiten (da dann die Instanz jedes mal neustartet). Macht der Admin ja auch so.

> Die API gibt das ja eigentlich her (duration), daher sollte das doch umsetzbar sein?

Ja, und wenn man eine dynamische App haben möchte, wo man alles selbst bestimmt, legt man eine Experten-App an. Da kann man die Dauer dann über einen Datenpunkt steuern. Geht schon alles.
