### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by jensfr1** [klein0r/ioBroker.awtrix-light#14]
### The problem

Apps which are created via the Instance will not be deleted if I change the name. 
e.g. Created an App "Test" which I then renamed into "Wetter" Both Apps were still active and I had to manually delete the app in the objects list 

### Version of nodejs

16.19.1

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.008

### Operating system running ioBroker

Debian

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Just use lower case letters for app names
