### ISSUE TITLE
mit V1.2.1 linker Text nicht mehr sichtbar

### ISSUE THREAD

**Issue by bahnuhr** [klein0r/ioBroker.awtrix-light#144]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Version of awtrix-light firmware

1.2.1

### The problem

![image](https://github.com/user-attachments/assets/be63e4da-18cc-4a0f-bcc1-5f1be65a1784)

Der linke Teil ist nicht sichtbar.

beta hab ich nicht getestet

### Version of nodejs

20.15.0

### Version of ioBroker js-controller

5.0.19

### Version of adapter

1.2.1

**Comment by klein0r** [comment]
Das ist dann aber ein Admin-Issue. Der baut die jsonConfig auf. Welche Admin-Version?

**Comment by bahnuhr** [comment]
Durch die Diskussion mit sayit bin ich auf Empfehlung von bluefox auf beta admin 7.0.13.

**Comment by klein0r** [comment]
Okay, dann bitte dort Issue öffnen
