### ISSUE TITLE
Save new Apps

### ISSUE THREAD

**Issue by jensfr1** [klein0r/ioBroker.awtrix-light#15]
### The problem

With Version 0.0.10 when I want to change the text of an existing app the Save Option does not show up. I have to add a new app in order to be able to change an existing app. 

### Version of nodejs

16.19.1

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.0.10

### Operating system running ioBroker

Debian

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

Let me know if you need more.

**Comment by klein0r** [comment]
There is a new validator which just allows lower case letters in the app name and the app name must be unique
