### ISSUE TITLE
Falscher Wert bei appDisplayTime

### ISSUE THREAD

**Issue by mcuiobroker** [klein0r/ioBroker.awtrix-light#16]
### The problem

Falscher Wert bei appDisplayTime.
Man gibt 2 ein und es wird 2000 angezeigt.

### Version of nodejs

18.16.0

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.0.10

### Operating system running ioBroker

raspian

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

Log nicht notwendig.

![awtrix FalscherWert appDisplayTime](https://github.com/klein0r/ioBroker.awtrix-light/assets/84818934/3692cd5c-7abe-494a-b788-43cbe0a6a224)

**Comment by klein0r** [comment]
Naja, man muss den Wert aber in Sekunden setzen. Nur was zurück kommt ist in Millisekunden. Habe mal einen Issue aufgemacht: https://github.com/Blueforcer/awtrix-light/issues/177

**Comment by klein0r** [comment]
Fixed with firmware 0.69
