### ISSUE TITLE
[Bug]: Can't update or add new items (buttons greyed out)

### ISSUE THREAD

**Issue by andiweli** [klein0r/ioBroker.awtrix-light#164]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Version of awtrix-light firmware

0.96

### The problem

I have 4 ioBroker items on my Ulanzi device, but can't edit them now and can't add a fifth one.
![fehler](https://github.com/user-attachments/assets/79214833-ea9d-46b0-842a-5268672cbaa0)

I already have restarted the adapter, without success.
Adapter is green and working and display shows the 4 items.
Save/Save&Close is disabled in ioBroker.

### iobroker.current.log (in debug mode!)
[log.txt](https://github.com/user-attachments/files/17203051/log.txt)
![log](https://github.com/user-attachments/assets/80ee80e3-fa22-41db-989b-bcc1703a600e)

### Version of nodejs

20.17.0

### Version of ioBroker js-controller

6.0.11

### Version of adapter

1.3.0

**Comment by hsteinme** [comment]
Does it work again if you enter a valid object ID or a constant text in the Object field of customerxxx?

**Comment by andiweli** [comment]
I had to restart the Admin adapter too - now it is working again.
Sorry.

Am Di., 1. Okt. 2024 um 12:07 Uhr schrieb Helmut ***@***.***>:

**Comment by hsteinme** [comment]
@andiweli Thus you can close this issue now.

**Comment by klein0r** [comment]
When you use `%s` or `%u`, you have to specify an object id as source for that placeholders. Remove those placeholders or select an object id.

<img width="993" alt="Screenshot 2024-10-02 at 09 53 44" src="https://github.com/user-attachments/assets/dfd0449e-b119-46b9-a06a-42c06f899249">
