### ISSUE TITLE
[Feature Request] Use 2 different values for 1 app

### ISSUE THREAD

**Issue by andiweli** [klein0r/ioBroker.awtrix-light#165]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Version of awtrix-light firmware

0.96

### The problem

My battery system for solar power has two different objects in ioBroker:
One item for charging (packInputPower), one for discharging (outputPackPower).

The batteries can either be charged or discharged - not both at the same time.

It would be great to have ONE app - but either show a charging animation together with the value of the charging-object - or shows a discharging animation with the other value of the discharging-object.

If this is not possible, perhaps two apps, but only one is shown that is active.

### Version of nodejs

20.17.0

### Version of ioBroker js-controller

6.0.11

### Version of adapter

1.3.0

**Comment by hsteinme** [comment]
You can do both yourself with the current ioBroker on-board means:

- If you want to display two apps alternately, use a script to switch their data points awtrix-light.[instance].apps.[appname].visible back and forth appropriately when changing between loading and unloading.

- If you want to use both display types in a joint expert app, you can use a script to set the data points awtrix-light.[instance].apps.[appname].icon (and also awtrix-light.[instance].apps.[appname].text if necessary) appropriately when changing between loading and unloading.

**Comment by andiweli** [comment]
I used a Blockly script now and it seems to work.

But the sort order is mixed up now.
It doesn't match the order I set in the adapter and doesn't match the order A>Z in objects.

**Comment by andiweli** [comment]
> Have you already tried "Is it possible to re-order apps?" in https://github.com/klein0r/ioBroker.awtrix-light/blob/master/docs/en/README.md?

Yes, I already moved them up and down. It is set as mentioned above "set in adapter".
 
> invalid jsonConfig: Please create an extra issue for this topic.

Done.

**Comment by andiweli** [comment]
Nevermind, found the "Position" input field :) Works now as expected :)

**Comment by andiweli** [comment]
Since the adapter has an option for an alternative icon why no option for an alternative value?

So the question was placed perfect! 👍🏻 No reason to be the "guard" 😉

I already have fixed it with an additional script.

**Comment by hsteinme** [comment]
I'm not a guard, I try to be a friendly helper - for users and for developers.

**Comment by klein0r** [comment]
As @hsteinme already said, it is possible to achieve this by using any logic adapter. 

> It would be great to have ONE app - but either show a charging animation together with the value of the charging-object - or shows a discharging animation with the other value of the discharging-object.

Just create a new state in `0_userdata.0` and calculate the value e.g. with the javascript adapter based on the other states
