### ISSUE TITLE
[Bug]: Die Uhr reagiert nicht auf Apps Visible oder activate.

### ISSUE THREAD

**Issue by MeisterQ** [klein0r/ioBroker.awtrix-light#167]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Version of awtrix-light firmware

0.96

### The problem

Die Uhr reagiert nicht auf Apps Visible oder activate. Im Log gibts no response.

Beim Prüfen vom Update kommt Err CNCT.

Ab und zu geht der Adapter auf Warning und startet neu, sodass wieder das IOBroker Symbol auf dem Display zu sehen ist.

Ich möchte abhängig von einem Datenpunkt per JS 3 Apps umschalten. Dabei sollen aber immer die anderen Apps deaktiviert werden, weil ich nicht das Scrollen zwischen den Apps haben will. Der DP aktualisiert sich nur 1x in 5 Minuten, daher gehe ich nicht von überlastung aus.

```
function updateDisplay() {
    let dirValue = getState(dir).val;
    if (getState(valid).val === true) {
        if (dirValue >= 5) {
            setState(raise, true, true);
            setState(drop, false, true);
            setState(stable, false, true)
        }
        else if (dirValue <= -5) {
            setState(drop, true, true);
            setState(raise, false, true);
            setState(stable, false, true)
        }
        else {
            setState(stable, true, true)
            setState(drop, false, true);
            setState(raise, false, true);
        }
    }
}
```

Selbst wenn das Skript deaktiviert ist, und ich die Custom Apps versuche per Hand umzuschalten, erscheinen sie nicht.

Die Standard Apps funktionieren.

### iobroker.current.log (in debug mode!)

awtrix-light.0 | 2024-10-11 08:50:53.102 | info | error ECONNABORTED from stats: timeout of 3000ms exceeded
-- | -- | -- | --
awtrix-light.0 | 2024-10-11 08:49:47.287 | warn | (doupdate)  Unable to execute firmware update (maybe this is already the newest  version): AxiosError: Request failed with status code 404
awtrix-light.0 | 2024-10-11 08:49:47.287 | warn | received 404 response from doupdate with content: "NoUpdateFound"
awtrix-light.0 | 2024-10-11 08:49:45.902 | info | performing firmware update
awtrix-light.0 | 2024-10-11 08:49:42.502 | warn | [onStateChange] bzstable: (switch) Unable to execute action: AxiosError: Request failed with status code 500
awtrix-light.0 | 2024-10-11 08:49:42.502 | warn | received 500 response from switch with content: "FAILED"
awtrix-light.0 | 2024-10-11 08:49:42.289 | warn | [onStateChange] bzstable: (switch) Unable to execute action: AxiosError: Request failed with status code 500
awtrix-light.0 | 2024-10-11 08:49:42.289 | warn | received 500 response from switch with content: "FAILED"
awtrix-light.0 | 2024-10-11 08:49:41.955 | warn | [onStateChange] bzstable: (switch) Unable to execute action: AxiosError: Request failed with status code 500
awtrix-light.0 | 2024-10-11 08:49:41.954 | warn | received 500 response from switch with content: "FAILED"
awtrix-light.0 | 2024-10-11 08:49:41.878 | warn | [onStateChange] bzstable: (switch) Unable to execute action: AxiosError: Request failed with status code 500
awtrix-light.0 | 2024-10-11 08:49:41.878 | warn | received 500 response from switch with content: "FAILED"
awtrix-light.0 | 2024-10-11 08:49:41.172 | warn | [onStateChange] bzstable: (switch) Unable to execute action: AxiosError: Request failed with status code 500
awtrix-light.0 | 2024-10-11 08:49:41.171 | warn | received 500 response from switch with content: "FAILED"
awtrix-light.0 | 2024-10-11 08:49:40.293 | warn | [onStateChange] bzstable: (switch) Unable to execute action: AxiosError: Request failed with status code 500
awtrix-light.0 | 2024-10-11 08:49:40.292 | warn | received 500 response from switch with content: "FAILED"
awtrix-light.0 | 2024-10-11 08:48:58.671 | info | rebooting device

### Version of nodejs

20.13.1

### Version of ioBroker js-controller

6.0.11

### Version of adapter

1.3.0

**Comment by klein0r** [comment]
> Ich möchte abhängig von einem Datenpunkt per JS 3 Apps umschalten.

1. Warum sollte man das machen? Dafür gibt es doch die Experten-Apps.
2. Setzt Du alle Datenpunkte bestätigt. Da passiert logischerweise auch nichts.
3. Bitte ein komplettes Debug-Log teilen

**Comment by MeisterQ** [comment]
Ich kann den Fehler gerade nicht reproduzieren, weil ich die Uhr neu geflashed habe kurz bevor ich den Issue aufgemacht habe.

Die Experten Apps kannte ich noch nicht. Wurden in deinem Video nicht weiter besprochen oder?

Datenpunkte setze ich bestätigt ja. Da reicht doch setState(state, true, true) oder?

[debuglog.txt](https://github.com/user-attachments/files/17339095/debuglog.txt)

**Comment by klein0r** [comment]
> Datenpunkte setze ich bestätigt ja.

Bitte die Grundlagen anschauen: https://haus-automatisierung.com/iobroker-kurs/
