### ISSUE TITLE
Fällt der Ulanzi TC001 aus / wird abgeschaltet & neu angeschaltet -> falsche Daten in den Objekten

### ISSUE THREAD

**Issue by mcuiobroker** [klein0r/ioBroker.awtrix-light#17]
### The problem

Startet man den TC001 neu, wird es im Adapter erkannt. (siehe unten LOG)
Aber die Apps, die vorher evtl. ausgeschaltet (visible=false) waren, werden bei Neustart im TC001 wieder automatisch aktiviert.
Diese Änderung wird aber nicht in den Objekten angezeigt.
Die Objektwerte bleiben, wie eingestellt (visible=false).
Es fehlt ein Einlesen der Objektwerte bei Neustart?
Startet man den Adapter bzw. die Instanz neu , so werden die Daten korrekt eingelesen.

### Version of nodejs

18.16.0

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.0.10

### Operating system running ioBroker

raspbian

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

```
awtrix-light.0 | 2023-06-07 21:55:20.393 | info | error ECONNABORTED from /api/stats: timeout of 3000ms exceeded
```

**Comment by klein0r** [comment]
Visible fliegt in der nächsten Version des Adapter raus, weil deprecated von der firmware: https://github.com/Blueforcer/awtrix-light/issues/178

**Comment by mcuiobroker** [comment]
Ehrlich gesagt fand ich es sehr gut mit dem `visible`. Da hatte man noch die Chance es selber nach Reboot durch ein kleines Script zurückzusetzen oder je nach Wunsch im Ablauf einzustellen. Geht jetzt leider nicht mehr. Schade.
