### ISSUE TITLE
Feature: Ram-Wert mit ins Json bzw. in die Objekte?

### ISSUE THREAD

**Issue by mcuiobroker** [klein0r/ioBroker.awtrix-light#18]
### The problem

Ram-Wert aufnehmen in die Objekte.
evtl auch wifi usw.

### Version of nodejs

18.16.0

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.0.10

### Operating system running ioBroker

raspbian

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

![image](https://github.com/klein0r/ioBroker.awtrix-light/assets/84818934/99996bb2-21dd-4bc8-8507-896ca6705e82)
![image](https://github.com/klein0r/ioBroker.awtrix-light/assets/84818934/b6d54dc9-8392-4ea2-bec2-f281ab8c3cd2)

**Comment by klein0r** [comment]
Bei mir steht in RAM gerade `150908`. In welcher Einheit ist das denn? Der ESP32 hat ja glaube ich 520 kB? Also Byte?

**Comment by mcuiobroker** [comment]
Habe nochmal bei Blueforcer nachgefragt:
![image](https://github.com/klein0r/ioBroker.awtrix-light/assets/84818934/3a99e01d-8a22-4f85-b313-6c4254f8e9d4)
Also nicht usedRam sondern freeRam.
Bitte korrigieren. Danke.
