### ISSUE TITLE
Kann keine Apps hinzufügen

### ISSUE THREAD

**Issue by SvenK84** [klein0r/ioBroker.awtrix-light#19]
### The problem

Habe heute ganz frisch Awtrix Light installiert und danach deinen ioBroker Adapter.
Wenn ich die IP eintrage kann ich speichern und der Adapter verbindet zur Ulanzi.
Wenn ich dann allerdings Apps erstellen will, bleibt der "Speichern" Button grau bzw. rot umrandet und ich kann nicht speichern.

![awtrix_light_iobroker_bug](https://github.com/klein0r/ioBroker.awtrix-light/assets/101870234/9eba92fa-c10b-4ddf-b2b3-1490f02a5a9e)

Kein Log-File angehängt.

### Version of nodejs

18.16.0

### Version of ioBroker js-controller

 4.0.24

### Version of Adapter

0.0.13

### Operating system running ioBroker

Ubuntu unter Proxmox

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
> Wenn ich dann allerdings Apps erstellen will, bleibt der "Speichern" Button grau bzw. rot umrandet und ich kann nicht speichern.

Ja, weil der Appname nur Kleinbuchstaben zulässt. Daher auch der rote Balken da drunter... _Dass die Fehlermeldung nicht angezeigt wird, ist ein Bug im Admin-Adapter_

https://github.com/ioBroker/ioBroker.admin/issues/1911
