### ISSUE TITLE
Config lässt sich nicht speichern 

### ISSUE THREAD

**Issue by Pauli29** [klein0r/ioBroker.awtrix-light#22]
### The problem

Änderungen in der config einer Instanz lassen sich nicht speichern 
Die beiden Button sind inaktiv und mit einem roten Rahmen.

### Version of nodejs

18.16.0⅙

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.0.14

### Operating system running ioBroker

Raspbian

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by Bjrow** [comment]
Hast du drauf geachtet, dass der Name nur Kleinbuchstaben haben darf?

**Comment by Pauli29** [comment]
Das war tatsächlich das Problem, danke!

Beste Grüße

Paul Reinhart
________________________________
Von: Bjrow ***@***.***>
Gesendet: Sonntag, 11. Juni 2023 22:26
An: klein0r/ioBroker.awtrix-light
Cc: Pauli29; Author
Betreff: Re: [klein0r/ioBroker.awtrix-light] Config lässt sich nicht speichern (Issue #22) 

Hast du drauf geachtet, dass der Name nur Kleinbuchstaben haben darf?

**Comment by klein0r** [comment]
> Das war tatsächlich das Problem, danke!

Bitte das nächste mal die Dokumentation lesen und suchen, ob es schon Issues zu dem Thema gibt/gab. Beides hätte zu einem Ergebnis geführt.

Duplicate of #19
