### ISSUE TITLE
Reorder Apps doesn´t work

### ISSUE THREAD

**Issue by chmaryniok** [klein0r/ioBroker.awtrix-light#24]
### The problem

When I try to reorder my apps, it will not be reordered on the watch.
I tried to add a new App and moved it to the second spot, but on the watch it will be the last item,
So I need to delete all Apps and create them in the order right now.

Would it be possible to add an object "index" to each app Item so you can rearrange the items in objects direct?

### Version of nodejs

16-19-1

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.0.16

### Operating system running ioBroker

Linux 

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
> Would it be possible to add an object "index" to each app Item so you can rearrange the items in objects direct?

That feature already exists, but is experimental in the firmware: https://github.com/Blueforcer/awtrix-light/blob/a96ce12366584bc1b423093d2206654754052252/docs/api.md?plain=1#L103

It will be implemented if the feature is stable

**Comment by chmaryniok** [comment]
Ok, also ist die Sortierung UI seitig vorbereitet aber noch nicht implementiert. 
BUG --> Feature Request

**Comment by klein0r** [comment]
> Ok, also ist die Sortierung UI seitig vorbereitet aber noch nicht implementiert.

Naja das ist halt einfach eine normale Tabelle vom Admin-Adapter. Die Reihenfolge spielt halt keine Rolle aktuell. Ich muss dann auch testen, ob man die Position einfach jedes Mal mitsenden kann / die Position für bestehende Apps ändern kann. Ansonsten müsste ich die Apps ja immer erst löschen und dann neu anlegen. Das wäre echt mühsam.
