### ISSUE TITLE
Geschwindigkeit der Laufschrift zu ändern

### ISSUE THREAD

**Issue by sansonifabio** [klein0r/ioBroker.awtrix-light#26]
### The problem

I have a question

Hallo@klein0r,

Gibt es eine Möglichkeit die Geschwindigkeit der Laufschrift zu ändern oder es möglich zu machen?
Grüße
Fabio

Hallo@klein0r,

Gibt es eine Möglichkeit, die Scrollgeschwindigkeit zu ändern oder zu ermöglichen?
Grüße
Fabio

### Version of nodejs

18.16.0

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.1.0

### Operating system running ioBroker

Debian

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
> Gibt es eine Möglichkeit die Geschwindigkeit der Laufschrift zu ändern oder es möglich zu machen?

Du meinst in den Apps? Aktuell nicht. Möglich machen ginge schon - nur das wird dann total unübersichtlich. Der nächste fragt dann nach einem weiteren Parameter usw. Am Ende sind 20 Parameter in der Tabelle.

**Comment by sansonifabio** [comment]
Guten Morgen,
nein ich meine im Adapter selber, sprich im Blockly Baustein und zwar nur für Text der von links nach rechts scrollt. Ist schon ein ziemlich Tempo was er an den Tag legt.

**Comment by klein0r** [comment]
> Ist schon ein ziemlich Tempo was er an den Tag legt.

Ja, der wird ja auch immer länger 😄  Habe in den letzten Versionen erst Rainbow und die Farbauswahl hinzugefügt.

**Comment by sansonifabio** [comment]
.... alle gut wenn das nicht geht. Evtl. könnte man es auch in die Adapter Einstellungen einbringen als einen einzigen Wert in Sec. 
Herzliche Grüße und vielen Dank Matthias 👍👍👍👌

**Comment by klein0r** [comment]
Klar könnte ich das machen - nur dann kommen 100%ig Anforderungen dass das pro App und pro Notification gehen sollte 😄

**Comment by klein0r** [comment]
Added in version 0.3.0
