### ISSUE TITLE
Adapter not in beta or stable repository

### ISSUE THREAD

**Issue by fischl3r** [klein0r/ioBroker.awtrix-light#27]
### The problem

Der Adapter lässt sich nicht mehr installieren. 
Der Adapter tauch weder im 
- beta (http://download.iobroker.net/sources-dist-latest.json) noch in der 
- stable (http://download.iobroker.net/sources-dist.json) Repo auf. 

### Version of nodejs

16.20.0

### Version of ioBroker js-controller

5.0.5

### Version of Adapter

0

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by fischl3r** [comment]
Ich habe versucht es laut README.md zu installieren.
<img width="359" alt="image" src="https://github.com/klein0r/ioBroker.awtrix-light/assets/34604223/29068883-bbfa-4d01-b8ea-ce7be056c320">
 Dort steht ja auch Beta... also sollte ich doch weniger die README lesen  


Please use the "adapter list" in ioBroker to install a stable version of this adapter. 
You can also use the CLI to install this adapter:

iobroker add awtrix-light

CLI: 
/opt/iobroker$ iobroker add awtrix-light
host.srv-iobroker Unknown packetName awtrix-light. Please install packages from outside the repository using npm!
/opt/iobroker$

**Comment by klein0r** [comment]
> Dort steht ja auch Beta... also sollte ich doch weniger die README lesen

Beta = letzte Version auf npm. Heißt aber nicht, dass der Adapter auch in der Beta Adapter-Liste steht.

Die README ist für alle meine Adapter gleich und wird nicht nach Entwicklungsstand angepasst, weil ja die Alpha-Tester (da sind wir gerade) wissen, wie man mit solchen frühen Adaptern umgeht.

Also gibt es gar kein Problem mit der Installation?
