### ISSUE TITLE
Instanz restartet sich periodisch - ioBroker hat ihn komplett gestoppt

### ISSUE THREAD

**Issue by marlan99** [klein0r/ioBroker.awtrix-light#28]
### The problem

Ich habe zwei Instanzen mit zwei Displays am laufen. Die Instanz 0 restartet seit V0.1.0 öfters neu und nun soeben von ioBroker komplett gestoppt.

folgende Meldungen finde ich im Protokoll auf Loglevel info:

`

awtrix-light.0 | 2023-06-22 08:35:55.800 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
awtrix-light.0 | 2023-06-22 08:35:55.797 | info | terminating
awtrix-light.0 | 2023-06-22 08:35:55.789 | error | Exception-Code: ECONNABORTED: timeout of 3000ms exceeded
awtrix-light.0 | 2023-06-22 08:35:55.788 | error | AxiosError: timeout of 3000ms exceeded at RedirectableRequest.handleRequestTimeout (/opt/iobroker/node_modules/iobroker.awtrix-light/node_modules/axios/dist/node/axios.cjs:3047:16) at RedirectableRequest.emit (node:events:513:28) at Timeout.<anonymous> (/opt/iobroker/node_modules/follow-redirects/index.js:169:12) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
awtrix-light.0 | 2023-06-22 08:35:55.787 | error | unhandled promise rejection: timeout of 3000ms exceeded
awtrix-light.0 | 2023-06-22 08:35:55.786 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
awtrix-light.0 | 2023-06-22 08:35:52.632 | error | [setApiConnected] Unable to update apps: AxiosError: timeout of 3000ms exceeded
awtrix-light.0 | 2023-06-22 08:35:52.624 | info | error ECONNABORTED from /api/apps: timeout of 3000ms exceeded
awtrix-light.0 | 2023-06-22 08:35:48.685 | info | Starting - connecting to http://192.168.1.209/
awtrix-light.0 | 2023-06-22 08:35:48.622 | info | starting. Version 0.1.0 (non-npm: klein0r/ioBroker.awtrix-light) in /opt/iobroker/node_modules/iobroker.awtrix-light, node: v16.19.1, js-controller: 4.0.24
host.iobroker | 2023-06-22 08:35:46.567 | info | instance system.adapter.awtrix-light.0 started with pid 10978
host.iobroker | 2023-06-22 08:35:16.458 | info | Restart adapter system.adapter.awtrix-light.0 because enabled
host.iobroker | 2023-06-22 08:35:16.455 | error | instance system.adapter.awtrix-light.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
awtrix-light.0 | 2023-06-22 08:35:15.808 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
awtrix-light.0 | 2023-06-22 08:35:15.807 | info | terminating
awtrix-light.0 | 2023-06-22 08:35:15.802 | error | Exception-Code: ECONNABORTED: timeout of 3000ms exceeded
awtrix-light.0 | 2023-06-22 08:35:15.801 | error | AxiosError: timeout of 3000ms exceeded at RedirectableRequest.handleRequestTimeout (/opt/iobroker/node_modules/iobroker.awtrix-light/node_modules/axios/dist/node/axios.cjs:3047:16) at RedirectableRequest.emit (node:events:513:28) at Timeout.<anonymous> (/opt/iobroker/node_modules/follow-redirects/index.js:169:12) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
awtrix-light.0 | 2023-06-22 08:35:15.799 | error | unhandled promise rejection: timeout of 3000ms exceeded
awtrix-light.0 | 2023-06-22 08:35:15.799 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
awtrix-light.0 | 2023-06-22 08:35:15.797 | info | error ECONNABORTED from /api/indicator1: timeout of 3000ms exceeded
awtrix-light.0 | 2023-06-22 08:35:08.875 | info | Starting - connecting to http://192.168.1.209/
awtrix-light.0 | 2023-06-22 08:35:08.815 | info | starting. Version 0.1.0 (non-npm: klein0r/ioBroker.awtrix-light) in /opt/iobroker/node_modules/iobroker.awtrix-light, node: v16.19.1, js-controller: 4.0.24
host.iobroker | 2023-06-22 08:35:06.317 | info | instance system.adapter.awtrix-light.0 started with pid 10765
host.iobroker | 2023-06-22 08:34:36.179 | info | Restart adapter system.adapter.awtrix-light.0 because enabled
host.iobroker | 2023-06-22 08:34:36.169 | error | instance system.adapter.awtrix-light.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
awtrix-light.0 | 2023-06-22 08:34:35.524 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
awtrix-light.0 | 2023-06-22 08:34:35.522 | info | terminating
awtrix-light.0 | 2023-06-22 08:34:35.503 | error | Exception-Code: ECONNABORTED: timeout of 3000ms exceeded
awtrix-light.0 | 2023-06-22 08:34:35.503 | error | AxiosError: timeout of 3000ms exceeded at RedirectableRequest.handleRequestTimeout (/opt/iobroker/node_modules/iobroker.awtrix-light/node_modules/axios/dist/node/axios.cjs:3047:16) at RedirectableRequest.emit (node:events:513:28) at Timeout.<anonymous> (/opt/iobroker/node_modules/follow-redirects/index.js:169:12) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
awtrix-light.0 | 2023-06-22 08:34:35.502 | error | unhandled promise rejection: timeout of 3000ms exceeded
awtrix-light.0 | 2023-06-22 08:34:35.501 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
awtrix-light.0 | 2023-06-22 08:34:35.498 | info | error ECONNABORTED from /api/indicator1: timeout of 3000ms exceeded
awtrix-light.0 | 2023-06-22 08:33:32.270 | info | error ECONNABORTED from /api/stats: timeout of 3000ms exceeded
javascript.0 | 2023-06-22 08:31:16.574 | error | script.js.VISU_Funktionen.Awtrix_Akkustand_anzeigen_JS: API is not connected (device offline ?)
awtrix-light.0 | 2023-06-22 08:30:32.266 | info | error ECONNABORTED from /api/stats: timeout of 3000ms exceeded
javascript.0 | 2023-06-22 08:29:19.639 | error | script.js.VISU_Funktionen.Awtrix_Akkustand_anzeigen_JS: {'message':'timeout of 3000ms exceeded','name':'AxiosError','stack':'AxiosError: timeout of 3000ms exceeded\n at RedirectableRequest.handleRequestTimeout (/opt/iobroker/node_modules/iobroker.awtrix-light/node_modules/axios/dist/node/axios.cjs:3047:16)\n at RedirectableRequest.emit (node:events:513:28)\n at Timeout.<anonymous> (/opt/iobroker/node_modules/follow-redirects/index.js:169:12)\n at listOnTimeout (node:internal/timers:559:17)\n at processTimers (node:internal/timers:502:7)','config':{'transitional':{'silentJSONParsing':true,'forcedJSONParsing':true,'clarifyTimeoutError':false},'adapter':['xhr','http'],'transformRequest':[null],'transformResponse':[null],'timeout':3000,'xsrfCookieName':'XSRF-TOKEN','xsrfHeaderName':'X-XSRF-TOKEN','maxContentLength':-1,'maxBodyLength':-1,'env':{'Blob':null},'headers':{'Accept':'application/json, text/plain, */*','Content-Type':'application/json','User-Agent':'axios/1.4.0','Content-Length':'100','Accept-Encoding':'gzip, compress, deflate, br'},'method':'post','data':'{\'text\':\'64.9 %\',\'icon\':\'a21585\',\'repeat\':1,\'duration\':300,\'stack\':false,\'wakeup\':false,\'hold\':true}','baseURL':'http://192.168.1.209:80','url':'/api/notify','responseType':'json'},'code':'ECONNABORTED','status':null}

`

### Version of nodejs

v16.19.1

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.1.0

### Operating system running ioBroker

Raspbian

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Please test with 0.1.1

**Comment by marlan99** [comment]
seems to be solved. at least no restart in the last 3 hours anymore
