### ISSUE TITLE
Userdefined Apps: no captial letters possible

### ISSUE THREAD

**Issue by amg666** [klein0r/ioBroker.awtrix-light#30]
### The problem

Hi, when I try to add an app and I use one ore more capital letters in the app name, the buttons "save" and "save&close" will not be activated, so I cannot save the new app. Using small letters works

### Version of nodejs

18.16.0

### Version of ioBroker js-controller

5.0.5

### Version of Adapter

0.1.1

### Operating system running ioBroker

Debian Bullseye, proxmox container

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Works as expected and documented

https://github.com/klein0r/ioBroker.awtrix-light/blob/3d2b763cac53e6e20e94da76edfa432f62b0f89e/docs/en/README.md?plain=1#L74-L76
