### ISSUE TITLE
feature request: blockly für das ansprechen der custom apps bereitstellen

### ISSUE THREAD

**Issue by Totte23** [klein0r/ioBroker.awtrix-light#35]
Hallo,

wäre es möglich ein Blockly für das Ansprechen der custom apps bereit zustellen?
Ganz simpler Baustein wo man den Namen der App angibet und ein JSON formatiertes dataset dranhängt...

beste Grüße

**Comment by klein0r** [comment]
Bitte mal ein Beispiel teilen was genau damit gemacht werden soll.

Warum nicht einfach selbst per HTTP eine custom app erstellen und füttern? Warum dann noch der Adapter?

**Comment by Totte23** [comment]
Danke für die schnelle Reaktion.

Ich möchte einfach per Blockly (weil dann nicht programmieren) custom apps per http POST ansprechen und befüllen.
Möchte da dann Progress Bar oder ähnliches mit darstellen.
Tatsächlich würde ich den Adapter dann gar nicht benötigen...

Bin mit JS Programmierung nicht sonderlich vertraut. Geht dann wahrscheinlich nur über exec? Oder?

**Comment by klein0r** [comment]
> Bin mit JS Programmierung nicht sonderlich vertraut.

Dynamisch JSON-Payloads zusammen zu bauen ist doch schon recht viel wissen 😄 Dann ist der Sprung zum eigenen HTTP-Request nicht mehr so groß...

> Geht dann wahrscheinlich nur über exec? Oder?

Exec führt Systembefehle aus. Du kannst wunderbar HTTP-Requests mit JavaScript stellen (macht der Adapter ja auch). Mit axios z.B.

**Comment by Totte23** [comment]
Habe es mittels axios erfolgreich aufgebaut....
Vielen Dank nochmal für die Tipps.
Falls das Ergebnis von Interesse ist, kann ich es gerne posten....
