### ISSUE TITLE
I can't add Apps within the ioBroker adapter

### ISSUE THREAD

**Issue by ChristianPi99** [klein0r/ioBroker.awtrix-light#36]
### The problem

I can't add custom apps within the adapter. I am using the latest version but when adding a new app, then the press "save" or "save & close" options are greyed out. I tried different settings, deleted the adapter and re-installed it. I erased the device and installed Awtrix Light again. But no luck.
The custom apps were working in a prior version. Could it be that some old settings are creating the problem within iobroker or on the device?

Thx for your help!

### Version of nodejs

v16.20.0

### Version of ioBroker js-controller

5.0.6

### Version of Adapter

v0.1.2

### Operating system running ioBroker

Raspberry Pi 4, Linx arm64

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

<img width="1238" alt="Bildschirmfoto 2023-07-05 um 00 09 55" src="https://github.com/klein0r/ioBroker.awtrix-light/assets/88233203/4f277b07-78f6-4933-927d-fb2e8eec8ca2">

**Comment by ChristianPi99** [comment]
my fault with the app name

**Comment by klein0r** [comment]
Duplicate of #19 #22
