### ISSUE TITLE
Feature Request: Option to copy instance settings (apps) if you have more then 1 AWTRIX running

### ISSUE THREAD

**Issue by bicmac** [klein0r/ioBroker.awtrix-light#37]
### The problem

I would like to have a easy way to copy the instance settings as i have more then 1 AWTRIX Light running and i dont want to add manual all apps to the instance again. or maybe you can add more then one device to a instance?
In addition it would be nice if we can sync to AWTRIX devices. Means that the show at the same time the same informations.

### Version of nodejs

16.19.0

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.31

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Supported since 0.4.0

https://github.com/klein0r/ioBroker.awtrix-light/blob/2c46b61cfe2bd2676fc4300e856e8834e3c669d6/docs/en/README.md?plain=1#L40-L48
