### ISSUE TITLE
Missings icons

### ISSUE THREAD

**Issue by SentiQ** [klein0r/ioBroker.awtrix-light#38]
### The problem

After updating from 0.2.0 to 0.3.2 (admin@6.6.0), no icons are shown.
Concerns old and new apps.

### Version of nodejs

18.16.1

### Version of ioBroker js-controller

5.0.6

### Version of Adapter

0.3.2

### Operating system running ioBroker

Docker

### Checklist of files to include below

- [ ] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

icon is always set to 5:

`sending "POST" request to "/api/custom?name=io" with data: {"background":"#000000","text":"1420 W","textCase":2,"repeat":1,"color":"#FFFFFF","scrollSpeed":100,"icon":5}`

**Comment by SentiQ** [comment]
<img width="1246" alt="Bildschirmfoto 2023-07-07 um 08 55 13" src="https://github.com/klein0r/ioBroker.awtrix-light/assets/10531678/168d0b42-bc04-4ab3-8e66-ca90143405c0">
<img width="1209" alt="Bildschirmfoto 2023-07-07 um 08 55 55" src="https://github.com/klein0r/ioBroker.awtrix-light/assets/10531678/713e51e1-4206-40e2-8fa0-15c499b4cec1">

**Comment by klein0r** [comment]
Thanks. This issue is not in version 0.3.2, but in the (untested and unreleased) change... Hopefully the adapter will be added to the beta repository ASAP.

Fixed in 0.3.3
