### ISSUE TITLE
apps laufen nur einmal automatisch durch und bleiben dann stehen

### ISSUE THREAD

**Issue by bicmac** [klein0r/ioBroker.awtrix-light#39]
[iobroker-log-ausschnitt.txt](https://github.com/klein0r/ioBroker.awtrix-light/files/11981376/iobroker-log-ausschnitt.txt)
### The problem

Ich habe bei mir 2 Custom Apps (für aussentemperatur und pooltemperatur) und dazu die normalen Zeit und Datum aktiviert.
Es laufen 2 Instanzen des Adapters. Die Apps laufen genau 1x durch mit der angegebenen Zeit. Dannach bleiben sie stehen. wie kann man denn einen dauercycle hinbekommen so das ich quasi immer im Abstand von X sekunden die nächste App sehen. Ich bilde mir ein das ging auch schonmal.

### Version of nodejs

v16.19.0

### Version of ioBroker js-controller

 4.0.24

### Version of Adapter

0.3.3

### Operating system running ioBroker

Debian GNU/Linux 10 (buster)

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by bicmac** [comment]
Steht auf "true"

**Comment by bicmac** [comment]
Hast Du schon ne Idee? Würde die gern wieder in Betrieb nehmen. Werd heute mal auf die neue 0.4 updaten vom Adapter. ggf hilft das ja

**Comment by klein0r** [comment]
Ne, wüsste nicht woran das liegt. Der Adapter bedient ja nur die Awtrix-Light und scrollt nicht den Text selbst durch. Kann also nur an den Settings liegen.

**Comment by bicmac** [comment]
ich habe jetzt 3 AWTRIX zurückgesetzt undneu geflasht. Dazu auch den kompletten Adapter neu installiert.

Bei allen das selbe. Sobald eine custom App über den Adapter dazu kommt App dazu kommt läuft er genau einmal durch und bleibt dann stehen sobald er die letzte App erreicht hat. 

AutoSwitch steht auf true.

<img width="2167" alt="image" src="https://github.com/klein0r/ioBroker.awtrix-light/assets/44036062/94d53e04-db6b-4fcb-a452-b986f2f71005">

<img width="2291" alt="image" src="https://github.com/klein0r/ioBroker.awtrix-light/assets/44036062/dfb6607b-a2fb-4244-9c63-894c1d9310a0">

Ich habe keine Idee warum er das macht.

**Comment by bicmac** [comment]
interessant ist auch das er das DisplayWeekdays = false nicht überträgt. Als wenn er keine Verbindung bekommt. Die Uhr ist aber im Netzwerk erreichbar. Im Log sehe ich auch nix.

**Comment by bicmac** [comment]
auch mit debug kommt nur das im log an

<img width="1816" alt="image" src="https://github.com/klein0r/ioBroker.awtrix-light/assets/44036062/eeba5ba3-1a09-4fc2-b8cc-cc796cefae8e">

**Comment by bicmac** [comment]
@klein0r hier mal das debug log.
Wenn ich den Adapter stoppe laufen die Uhr und das Datum (die beiden internen Apps also) weiter. Wenn ich den Adapter starte dann läuft der cyclus genau einmal durch und bleibt dann bei der custom app stehen.
Die Frage ist ob das an der AWTRIX FW liegt oder am Adpter.

[logfile.txt](https://github.com/klein0r/ioBroker.awtrix-light/files/12040640/logfile.txt)

**Comment by klein0r** [comment]
@bicmac Eventuell habe ich das `"noScroll": true` auch falsch verstanden?! Klappt es, wenn Du scrolling in der App aktivierst?

**Comment by Z18Aplha** [comment]
Es muss an dem Text Scrolling liegen. Ich habe das gleiche Problem. 
Solange der Text nicht zu lang ist, funktioniert die automatische App Rotation. Sobald der Text aber zu lang ist, der Haken "noScroll" gesetzt ist, verharrt das Display bei der App. Erst wenn der Text wieder aufs Display passt geht's weiter.

**Comment by klein0r** [comment]
Kann das jemand im Awtrix-Light Repo als Issue melden? Wäre super nett. Gern hierauf verlinken.

**Comment by bicmac** [comment]
Ich habe da schon ein issue offen
https://github.com/Blueforcer/awtrix-light/issues/216

Ich schaue morgen mal das ich die Infos von hier da mit anhänge (falls nicht jemand anderes bis dahin das da einfügt) bin nur grad unterwegs und konnte daher bisher selber nicht testen an meinen Clocks.

**Comment by bicmac** [comment]
@klein0r ich habe die Infos mal ans Ticket gehangen. Blueforcer fragt nach der RAW JSON die ans Device geschickt wird. Wie sehe ich die? Im DEBUG Mode vom Adapter? Oder kannst Du mir die zur Verfügung stellen? Bin noch immer unterwegs und komme nicht an mein System.
Momentan habe ich 3 Custom Apps am laufe + die 2 Internen Apps für Datum und Uhrzeit.
Die Custom Apps sind einmal aussentemp, einmal wassertemp und einmal den PH Wert vom pool.

**Comment by bicmac** [comment]
@klein0r , @Z18Aplha : hier die ANtwort von Blueforcer:

"wie ich mir dachte:

Sobald du "repeat" nutzt, wird die App nicht mehr nach einer Zeit beendet sondern dann wenn der Text X mal durchgescrollt ist.
Mit noScroll verhindert du es aber und die bedingung wird nie eintreten.

Ich könnte das evtl noch abfangen das bei noScroll wieder auf Zeit geschaut wird und nicht auf repeat.

Bis dahin kannst du repeat entfernen oder auf 0 setzen"

Werd das mit dem Workarround morgen mal testen. Er hat ja auch geschrieben das er es ggf in einer neuen Version abfangen kann.

**Comment by bicmac** [comment]
Update, wollt es doch gleich testen. ich kann repeat im Adapter nicht auf 0 setzen.
@klein0r kannst Du ggf 0 erlauben einem Fix?

**Comment by bicmac** [comment]
Hier noch ein Komentar von Blueforcer bezüglich der „repeat“ option die im iobroker adapter ja default 1 hat (soweit ich sehe) und auch nicht auf null gesetzt werden kann.

„Dann ist das aber generell falsch.
Repeat ist optional in awteix und sollte nicht Standardmäßig auf 1 sei.

In awteix ist es Standard 0 wenn's nicht angegeben wird“

**Comment by bicmac** [comment]
@klein0r Blueforcer hat den Bug auf Github grad geschlossen mit folgender Anmerkung:
„Sorry fehler von mir. Grad nochmal geschaut, -1 ist standard. Denn bei 0 ist er fertig mit scrollen“

**Comment by klein0r** [comment]
Ja okay und was soll man jetzt übermitteln?! Ich seh nicht mehr durch.

**Comment by bicmac** [comment]
Ich leider auch nicht. Ggf kannst du dich mal direkt mit Blueforcer in Verbindung setzten. Stille Post spielen ist glaub ich nicht wirklich gut hier

**Comment by bicmac** [comment]
@klein0r , @Z18Aplha nach dem Update der AWTRIX auf die neue FW und dem Update des Adapter auf die aktuelle Version sieht es bei mir jetzt gut aus. Von mir aus könnte der Bug geschlossen werden.
