### ISSUE TITLE
Pull Request - Matrix Datei Kompatibilität

### ISSUE THREAD

**Issue by JBSullivan** [klein0r/ioBroker.awtrix-light#40]
### The problem

Sorry, ich weiß das ich hier falsch bin, aber ich bekomme keinen Pull Request eröffnet.

Du entwickelst ja den ioB Adapter für die ULANZI TC001. Ich weiß nicht ob du ggf. dieses Projekt in ioBroker kennst ?
( https://forum.iobroker.net/topic/12811/esp-matrix-anzeige-fully-iobroker-steuerbar )

Ich habe das Projekt bei mir am laufen und via Blockly wird ein entsprechender Datenpunkt erzeugt, der an den WEMOS übertragen und abgespielt wird.

Ausschnitt:
![image](https://github.com/klein0r/ioBroker.awtrix-light/assets/44617472/28964fef-8a03-45aa-8fbf-4888328c51f0)

https://photos.google.com/share/AF1QipPy5fZduyeUfN3CDOcGXqP2NlYsZ_hn2A-0s0scBV7ZSuYNAtONI4JUwKtVCibxlA?key=QXJCY05WaFFRSWY0b2pNQ2tkM29fSThNVno2Q2xn

Der Datenpunkt sieht wie folgt aus:

`10.07.2023 - 13:28 Uhr;Wall-E: 61% - WORKING;Außentemperatur: 24.9 °C;Windgeschw. : 23.2 km/h;Gebäude Last: 849.04 Watt;Balkonkraftwerk: 348.8 Watt;#left Σ PV-Prod.: 3984 Watt;Speicher SoC: 72.2 %;10.07.2023 - 13:28 Uhr;Pool Temp.: 28.1 °C;Pool Status:  Solar;`

Ist es denkbar, das dein Adapter mit diesem Datenpunkt ebenfalls umgehen kann, sodaß die Basisdaten sowohl auf dem DOT Matrix, als auch auf dem ULANZI angezeigt werden können?

### Version of nodejs

18.15

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

noch nicht installiert

### Operating system running ioBroker

Windows

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Was wäre der Vorteil gegenüber mehreren Apps für all diese Datenpunkte?

*Außer, dass Du die nicht anlegen brauchst und die Arbeit an mich auslagerst* 😄

**Comment by JBSullivan** [comment]
Bitte nicht falsch verstehen - es geht nicht darum "Arbeit" auszulagern. Ich habe schon soviel an meinem ioB herum gebastelt, da käme es auf zusätzliche Arbeit für den ULANZI auch nicht mehr drauf an.

Da der ULANZI aktuell im Zulauf aus China ist, kann ich deinen Adapter z.Zt. auch gar nicht ausprobieren, um zu sehen, was alles an DP`s generiert wird und wie diese dann an den ULANZI geschickt werden.

Ich bin da also vollkommen unbedarft, was die Funktion deines Adapters betrifft.

Du fragst nach dem Vorteil - nun zum einen wäre es für alle User die auch mit dem DOT Matrix Display arbeiten, sehr leicht eine bestehende Datenbasis 1:1 auf dem ULANZI angezeigt zu bekommen. Wie du oben an dem Beispielvideo vielleicht gesehen hast, ist mein DOT Matrix Display fest (aber schwenkbar) im Außenbereich verbaut. Der ULANZI hat einen Akku und könnte in der Wohnung bei Bedarf überall mit hin genommen werden und dabei die gleichen Daten anzeigen, wie das fest verbaute DOT Matrix Display.

Beim DOT Matrix laufen die ausgewerteten DP`s, je nach Anzeigestatus, hintereinander weg durchs "Bild".  Wenn man das DOT Matrix schon länger im Einsatz hat, weiß man genau wann welcher Wert nach welcher Anzeige als nächstes kommt.

Ich vermute mal, das auch beim ULANZI die Datenpunkte als Laufschrift durchlaufen. Man müsste sich also nicht umgewöhnen, da die Datenbasis für beide Geräte die gleiche ist.

Wie gesagt, ich kenne deinen Adapter noch nicht. Vermutlich wird war aber auch bei dir ein Datenpunkt erstellt, der die Wunschwerte welche durchs Display laufen sollen, enthält. 

Wäre halt schön gewesen, wenn dieser DP genau so aufgebaut wäre, wie der des DOT Matrix Display bzw. wenn man den DOT Matrix Display DP, in deinen Adapter importieren könnte damit er dann in der Richtigen Formatierung an das ULANZI übertragen werden könnte.

Viele Könnte .... und wäre schön wenn... - wenn nicht dann nicht. War ja nur eine Idee.

**Comment by klein0r** [comment]
> Wie gesagt, ich kenne deinen Adapter noch nicht. Vermutlich wird war aber auch bei dir ein Datenpunkt erstellt, der die Wunschwerte welche durchs Display laufen sollen, enthält.

Nein, Du konfigurierst "Apps" in der Instanz und wählst einfach die Datenpunkte aus.
