### ISSUE TITLE
Feature request: Alternativen text beim Timer.

### ISSUE THREAD

**Issue by bicmac** [klein0r/ioBroker.awtrix-light#42]
### The problem

Kann man beim Time über Blockly ggf einen alternativen Text übergeben der angezeigt wird anstatt des "TIMER"

### Version of nodejs

16.19.0

### Version of ioBroker js-controller

16.19.0

### Version of Adapter

0.31

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Gibt die API nicht her: https://github.com/Blueforcer/awtrix-light/blob/359239799e01eb738ad41776ae145a90ecbe92f6/docs/api.md?plain=1#L310-L317

**Comment by bicmac** [comment]
Ich habe mal bei Blueforcer einen request aufgemacht das einzubauen. Evtl lässt er sich ja darauf ein.
