### ISSUE TITLE
Feature Request: Icon Position / Custom Apps deaktivierbar

### ISSUE THREAD

**Issue by JBSullivan** [klein0r/ioBroker.awtrix-light#45]
### The problem

So, heute ist nun auch mein ULANZI aus China eingetroffen und er wurde sofort mit der richtigen Firmware "bearbeitet"

Dabei hätte ich (aktuell) zwei Wünsche an den Adapter.

1.) Kann man in das Menü der Custom Apps noch eine Checkbox einbauen zum deaktivieren? Wenn man die App (vorerst) nicht anzeigen lassen möchte, heißt das aber nicht, das man alle Einstellungen dazu auch sofort löschen muss. Hier wäre eine Checkbox hilfreich, mit der man die App für die Anzeige, unter Beibehaltung der Einstellungen, deaktivieren kann.

..... und eben so eingefallen, die Möglichkeite die Reihenfolge der Custom Apps per Drag and Drop verschieben zu können, da dieses ja auch die Reihenfolge der Darstellung beeinflusst.

2.) Icon Verschieben - Wenn ich für die Pooltemperatur das  Wort "Pooltemperatur" verwende ist dieses ja schon sehr lang. Stattdessen würde ich mir wünschen, wenn man das Temp. Icon in seiner Position verschieben kann.

Sprich, statt dem langen Wort = "Pool-Temp.ICON" Dafür müsste man in den App Einstellungen festlegen können, ab der wievielten Matrix Stelle das Icon beginnen soll.  Jeder Buchstabe belegt 3 LED Felder + Leerzeichen. Ergibt für das Wort  Pool = 15 LED`s + Trennzeichen für die Startposition des Icon. Somit würde man im Adapter die Startpostion 17 für das Icon festlegen.

Keine Ahnung, ob das überhaupt machbar wäre.

### Version of nodejs

15.15

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.4.0

### Operating system running ioBroker

Windows

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
> Wenn man die App (vorerst) nicht anzeigen lassen möchte, heißt das aber nicht, das man alle Einstellungen dazu auch sofort löschen muss.

Mhhh, ja mal schauen, machen wir n Feature Request draus

> da dieses ja auch die Reihenfolge der Darstellung beeinflusst.

Kommt in die nächste Version

> Dafür müsste man in den App Einstellungen festlegen können, ab der wievielten Matrix Stelle das Icon beginnen soll.

Das kann die API nicht. Aber man kann festlegen, ob das Icon mit dem Text verschoben werden soll. Das könnte ich auch mit in die Optionen packen

**Comment by JBSullivan** [comment]
Eine Bitte hätte ich noch - könntest du die Checkbox "Apps löschen, wenn die Instanz gestoppt wird" in die Experteneinstellungen verlegen? Ich bin aus versehen drauf gekommen und habe es mit gespeichert. Da ich ALLE Serienmäßigen APPS ausgeschaltet habe, war plötzlich der Bildschirm dunkel und ich habe mir einen Ast gesucht, was mit dem Display los sein könnte.

**Comment by klein0r** [comment]
> könntest du die Checkbox "Apps löschen, wenn die Instanz gestoppt wird" in die Experteneinstellungen verlegen?

Ne, das finde ich sehr sinnvoll und hat mit "Experte sein" ja nichts zu tun. Sonst zeigt die Uhr ja ggf. veralteten Quatsch an.
