### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by JBSullivan** [klein0r/ioBroker.awtrix-light#46]
### The problem

Ich hatte das Problem gestern schon beim konfigurieren von neuen Apps und heute wieder.  Häufig - nicht immer - wenn man in der Instanz eine neue App parametrieren will, stürzt der Admin mit der "Error in Gui" Meldung ab.

KORRIGIERE: Sobald man heute das + Symbol für das anlegen von neuen APPs drückt, stürzt der Admin sofort mit der Error Meldung ab. Admin Version ist 6.6.1

Zu dem Zeitpunkt sind zwei (Chrome) Browser Tabs offen - einmal der Admin mit geöffneter JS Konsole und eben ein zweiter Tab mit den Instanz Einstellungen von Awtrix

`bootstrap.jsx:19 iobroker.admin@6.6.0
instrument.ts:132 [2023-07-18T07:59:23.300Z] Try to connect
instrument.ts:132 Stored version: , new version: 6.6.0
instrument.ts:132 Connected: true
instrument.ts:132 Double links: "vis.0/vis/edit.html" and "vis.0"
instrument.ts:132 Translate: Link
instrument.ts:132 Translate: time
instrument.ts:132 Translate: timeOffset
instrument.ts:132 Translate: _nodeCurrent
instrument.ts:132 Translate: _nodeNewest
instrument.ts:132 Translate: _nodeNewestNext
instrument.ts:132 Translate: _npmCurrent
instrument.ts:132 Translate: _npmNewest
instrument.ts:132 Translate: _npmNewestNext
instrument.ts:132 [ADAPTERS] getAdapters
instrument.ts:132 [ADAPTERS] getAdaptersInfo
instrument.ts:132 [ADAPTERS] admin
instrument.ts:132 system.adapter.admin.0
instrument.ts:132 system.adapter.alexa2.0
instrument.ts:132 system.adapter.awtrix-light.0
instrument.ts:132 system.adapter.backitup.0
instrument.ts:132 system.adapter.bring.0
instrument.ts:132 system.adapter.bydhvs.0
instrument.ts:132 system.adapter.daswetter.0
instrument.ts:132 system.adapter.device-reminder.0
instrument.ts:132 system.adapter.device-watcher.0
instrument.ts:132 system.adapter.devices.0
instrument.ts:132 system.adapter.deyeidc.0
instrument.ts:132 system.adapter.discovergy.0
instrument.ts:132 system.adapter.dwd.0
instrument.ts:132 system.adapter.email.0
instrument.ts:132 system.adapter.energiefluss.0
instrument.ts:132 system.adapter.energiefluss.1
instrument.ts:132 system.adapter.fb-checkpresence.0
instrument.ts:132 system.adapter.fritzdect.0
instrument.ts:132 system.adapter.fronius.0
instrument.ts:132 system.adapter.fullybrowser.0
instrument.ts:132 system.adapter.gartenbewaesserung.0
instrument.ts:132 system.adapter.gruenbeck.0
instrument.ts:132 system.adapter.ical.0
instrument.ts:132 system.adapter.ical.1
instrument.ts:132 system.adapter.icons-material-png.0
instrument.ts:132 system.adapter.icons-material-svg.0
instrument.ts:132 system.adapter.influxdb.0
instrument.ts:132 system.adapter.info.0
instrument.ts:132 system.adapter.innogy-smarthome.0
instrument.ts:132 system.adapter.iot.0
instrument.ts:132 system.adapter.javascript.0
instrument.ts:132 system.adapter.mihome-vacuum.0
instrument.ts:132 system.adapter.modbus.0
instrument.ts:132 system.adapter.mqtt.0
instrument.ts:132 system.adapter.mqtt.2
instrument.ts:132 system.adapter.node-red.0
instrument.ts:132 system.adapter.nuki-extended.0
instrument.ts:132 system.adapter.octoprint.0
instrument.ts:132 system.adapter.onvif.0
instrument.ts:132 system.adapter.pollenflug.0
instrument.ts:132 system.adapter.proxy.0
instrument.ts:132 system.adapter.pvforecast.0
instrument.ts:132 system.adapter.rflink.0
instrument.ts:132 system.adapter.roomba.0
instrument.ts:132 system.adapter.shelly.0
instrument.ts:132 system.adapter.shelly.1
instrument.ts:132 system.adapter.simple-api.0
instrument.ts:132 system.adapter.snmp.0
instrument.ts:132 system.adapter.socketio.0
instrument.ts:132 system.adapter.sonoff.0
instrument.ts:132 system.adapter.sourceanalytix.0
instrument.ts:132 system.adapter.spotify-premium.0
instrument.ts:132 system.adapter.sprinklecontrol.0
instrument.ts:132 system.adapter.tankerkoenig.0
instrument.ts:132 system.adapter.telegram.0
instrument.ts:132 system.adapter.tr-064.0
instrument.ts:132 system.adapter.trashschedule.0
instrument.ts:132 system.adapter.tronity.0
instrument.ts:132 system.adapter.vis.0
instrument.ts:132 system.adapter.vis-canvas-gauges.0
instrument.ts:132 system.adapter.vis-colorpicker.0
instrument.ts:132 system.adapter.vis-hqwidgets.0
instrument.ts:132 system.adapter.vis-icontwo.0
instrument.ts:132 system.adapter.vis-inventwo.0
instrument.ts:132 system.adapter.vis-jqui-mfd.0
instrument.ts:132 system.adapter.vis-justgage.0
instrument.ts:132 system.adapter.vis-map.0
instrument.ts:132 system.adapter.vis-materialdesign.0
instrument.ts:132 system.adapter.vis-plumb.0
instrument.ts:132 system.adapter.vis-timeandweather.0
instrument.ts:132 system.adapter.vw-connect.0
instrument.ts:132 system.adapter.web.0
instrument.ts:132 system.adapter.web.1
instrument.ts:132 system.adapter.wled.0
instrument.ts:132 system.adapter.zigbee.0
instrument.ts:132 getInstances: 491
instrument.ts:132 Translate: History Apps
instrument.ts:132 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at n.<anonymous> (index.jsx:176:49)
    at Ua (react-dom.production.min.js:144:189)
    at wi (react-dom.production.min.js:261:422)
    at ki (react-dom.production.min.js:260:446)
    at ki (react-dom.production.min.js:260:343)
    at bi (react-dom.production.min.js:259:431)
    at react-dom.production.min.js:283:96
    at Ss (react-dom.production.min.js:281:398)
    at as (react-dom.production.min.js:270:269)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)` 

### Version of nodejs

18.15

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.4.0

### Operating system running ioBroker

Windows

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Was auch immer Du machst, ist das ein Issue für den Admin-Adapter und nicht für das Repo hier, da der Adapter die Standard jsonConfig-Komponente verwendet.

> Double links: "vis.0/vis/edit.html"

Das deutet eher auf ein VIS Thema hin?

**Comment by JBSullivan** [comment]
OK ?!? Ich habe mir in der Zwischenzeit mal die Mühe gemacht, und bei alle 48 Adapter die ich am laufen habe, die Instanz Einstellungen geöffnet und dann in den jeweiligen Instanzen ein drin "rum geklickert".

Es kam nirgendwo zu einem Admin Absturz. Einzig der AWTRIX Adapter stürzt ab, wenn man nur das + Symbol in den App Einstellungen anklickt und dann die Maus ein Stück auf dem Bildschirm bewegt. Dann stürzt der Admin sofort mit der obigen Meldung ab.

Unter Firefox ist es das gleiche, allerdings gibt es da noch die Meldung "Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden."

Hier nochmal die F12 Meldungen von Firefox.  Ich mache gerne ein Issue beim Admin auf, aber es ist so extrem auffällig, das dieses Phänomen nur bei Aktionen auftritt, die an deinem Adapter vorgenommen werden.

`system.adapter.influxdb.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.info.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.innogy-smarthome.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.iot.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.javascript.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.mihome-vacuum.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.modbus.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.mqtt.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.mqtt.2 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.node-red.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.nuki-extended.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.octoprint.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.onvif.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.pollenflug.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.proxy.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.pvforecast.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.rflink.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.roomba.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.shelly.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.shelly.1 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.simple-api.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.snmp.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.socketio.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.sonoff.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.sourceanalytix.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.spotify-premium.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.sprinklecontrol.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.tankerkoenig.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.telegram.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.tr-064.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.trashschedule.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.tronity.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.vis.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.vis-canvas-gauges.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.vis-colorpicker.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.vis-hqwidgets.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.vis-icontwo.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.vis-inventwo.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.vis-jqui-mfd.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.vis-justgage.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.vis-map.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.vis-materialdesign.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.vis-plumb.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.vis-timeandweather.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.vw-connect.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.web.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.web.1 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.wled.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
system.adapter.zigbee.0 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
getInstances: 2838 [instrument.ts:132](http://10.122.60.87:8081/static/node_modules/@sentry/src/instrument.ts)
TypeError: can't convert null to object
    errorTimeout index.jsx:176
    React 8
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14`

**Comment by klein0r** [comment]
> die Instanz Einstellungen geöffnet und dann in den jeweiligen Instanzen ein bisschen drin "rum geklickert".

Okay, dann hilf gerne weiter und wir klären hier den Admin-Issue: Von der Fehlermeldung her würde ich sagen, das liegt an "instance" Komponente vom ioBroker admin, welche in diesem Fall mit `_dataSources` aufgerufen wird, um alle möglichen History-Adapter anzuzeigen (also Adapter, welche `getHistory` unterstützen).

Welche Adapter hast du noch im Einsatz, welche diese jsonComponente des Admin verwenden und welche davon laufen problemlos?

- https://github.com/ioBroker/ioBroker.admin/blob/v6.6.1/src/src/components/JsonConfigComponent/ConfigInstanceSelect.jsx
- https://github.com/ioBroker/ioBroker.admin/blob/506e759be8479c418ece18147eeecff92563ab83/src/src/components/JsonConfigComponent/SCHEMA.md?plain=1#L127-L132

Freue mich auf die Rückmeldung

**Comment by klein0r** [comment]
@JBSullivan Und?

**Comment by JBSullivan** [comment]
Ich würde gerne helfen, aber ich bin kein Entwickler sondern Endanwender. Habe mir die beiden Links angesehen, aber alles was da kommt, sind für mich Böhmische Dörfer. Ich kann dir nicht sagen, welche meiner Adapter diese json Componente verwenden.

Aktuell bin ich beim ULANZI auf 0.71 und bei deinem Adapter auf 0.6.0. 

Anlegen von neuen Apps ist unter Chrome und Firefox nicht mehr möglich, weil sofort (nach drücken des + Zeichen) der GUI Error kommt. Zwischendurch konnte ich mal an 1-2 Tagen Apps anlegen, ohne das der Error kam. Da war aber alles super zähflüssig. Wenn man einen App Namen mit 10 Buchstaben eingetippt hatte, konnte man getrost 10 -12 Sekunden warten und zusehen, wie Buchstabe für Buchstabe in die Eingabezeile geschrieben wurde.

Da habe ich es dann tatsächlich geschafft alle meine Apps anzulegen und entsprechend zu sortieren. Heute nach dem Update auf die 0.6.0, scheitert es schon beim + Zeichen drücken.

Hier die Liste meiner verwendeten Adapter. Wie gesagt, ich kann mit deinen beiden Links nichts anfangen wüsste jetzt nicht wie ich das heraus bekommen soll. Ist mit `getHistory` der History Adapter gemeint oder alle Adapter die ein Tracking von historischen Daten, z.B. auf Basis von influxDB zulassen?

Als dein Adapter noch ganz neu war, habe ich das mit den Historie Apps ausprobiert. Hat aber nicht funktioniert, bzw. ich habe nicht verstanden was man da machen soll. Ich habe das dann wieder gelöscht und nichts mehr weiter mit Historie gemacht.

Ich bin mir nicht ganz sicher, aber ich glaube seit dem stehen unter Histors Zwei Zeilen mit + Zeichen. Ich kann beide Zeilen öffnen, aber es stehen in beiden nur die Grundeinstellungen drin. Löschen kann ich sie auch nicht, weil dann sofort der GUI Error zuschlägt.

![image](https://github.com/klein0r/ioBroker.awtrix-light/assets/44617472/5e90ca16-b8a2-4001-b2d0-ebeedf2aad8e)


`C:\iobroker\GLT>iob update
Used repository: beta
Adapter    "admin"        : 6.6.3    , installed 6.6.1  [Updatable]
Adapter    "alexa2"       : 3.23.2   , installed 3.23.2
Adapter    "awtrix-light" : 0.6.0    , installed 0.6.0
Adapter    "backitup"     : 2.6.23   , installed 2.6.23
Adapter    "bring"        : 1.8.1    , installed 1.8.1
Adapter    "bydhvs"       : 1.4.0    , installed 1.4.0
Adapter    "daswetter"    : 3.1.8    , installed 3.1.8
Adapter    "device-reminder": 1.2.9  , installed 1.2.9
Adapter    "device-watcher": 2.9.3   , installed 2.9.3
Adapter    "devices"      : 1.1.5    , installed 1.1.5
Adapter    "discovergy"   : 0.5.8    , installed 0.5.8
Adapter    "discovery"    : 3.2.0    , installed 3.2.0
Adapter    "dwd"          : 2.8.5    , installed 2.8.5
Adapter    "email"        : 1.2.0    , installed 1.2.0
Adapter    "fb-checkpresence": 1.2.1 , installed 1.2.1
Adapter    "fritzdect"    : 2.3.1    , installed 2.3.1
Adapter    "fronius"      : 2.0.2    , installed 1.1.3  [Updatable]
Adapter    "fullybrowser" : 2.1.2    , installed 2.1.2
Adapter    "gruenbeck"    : 0.0.42   , installed 0.0.42
Adapter    "ical"         : 1.13.3   , installed 1.13.3
Adapter    "icons-material-png": 0.1.0, installed 0.1.0
Adapter    "icons-material-svg": 0.1.0, installed 0.1.0
Adapter    "influxdb"     : 3.2.0    , installed 3.2.0
Adapter    "info"         : 1.9.26   , installed 1.9.26
Adapter    "innogy-smarthome": 1.2.6 , installed 1.2.6
Adapter    "iot"          : 2.0.11   , installed 2.0.11
Adapter    "javascript"   : 7.1.1    , installed 7.1.1
Controller "js-controller": 5.0.9    , installed 5.0.8  [Updatable]
Adapter    "mihome-vacuum": 3.11.0   , installed 3.11.0
Adapter    "modbus"       : 5.0.11   , installed 5.0.11
Adapter    "mqtt"         : 4.1.1    , installed 4.1.1
Adapter    "node-red"     : 4.0.3    , installed 4.0.3
Adapter    "nuki-extended": 2.6.5    , installed 2.6.5
Adapter    "octoprint"    : 5.0.1    , installed 5.0.1
Adapter    "onvif"        : 1.0.5    , installed 1.0.5
Adapter    "pollenflug"   : 1.0.6    , installed 1.0.6
Adapter    "proxy"        : 1.3.2    , installed 1.3.2
Adapter    "pvforecast"   : 2.7.1    , installed 2.7.1
Adapter    "rflink"       : 2.1.6    , installed 2.1.6
Adapter    "roomba"       : 1.1.4    , installed 1.1.4
Adapter    "shelly"       : 6.4.1    , installed 6.4.1
Adapter    "simple-api"   : 2.7.2    , installed 2.7.2
Adapter    "snmp"         : 2.4.11   , installed 2.4.11
Adapter    "socketio"     : 6.4.0    , installed 6.4.0
Adapter    "sonoff"       : 2.5.7    , installed 2.5.7
Adapter    "sourceanalytix": 0.4.14  , installed 0.4.14
Adapter    "spotify-premium": 1.2.2  , installed 1.2.2
Adapter    "sprinklecontrol": 0.2.13 , installed 0.2.13
Adapter    "tankerkoenig" : 3.3.7    , installed 3.3.7
Adapter    "telegram"     : 1.16.0   , installed 1.16.0
Adapter    "tr-064"       : 4.2.18   , installed 4.2.18
Adapter    "trashschedule": 2.2.0    , installed 2.2.0
Adapter    "tronity"      : 1.1.1    , installed 1.1.1
Adapter    "vis"          : 1.4.16   , installed 1.4.16
Adapter    "vis-canvas-gauges": 1.0.1, installed 1.0.1
Adapter    "vis-colorpicker": 2.0.3  , installed 2.0.3
Adapter    "vis-hqwidgets": 1.4.0    , installed 1.4.0
Adapter    "vis-icontwo"  : 0.96.0   , installed 0.96.0
Adapter    "vis-inventwo" : 3.3.3    , installed 3.3.3
Adapter    "vis-jqui-mfd" : 1.0.12   , installed 1.0.12
Adapter    "vis-justgage" : 1.0.2    , installed 1.0.2
Adapter    "vis-map"      : 1.0.4    , installed 1.0.4
Adapter    "vis-materialdesign": 0.5.9, installed 0.5.9
Adapter    "vis-plumb"    : 1.0.2    , installed 1.0.2
Adapter    "vis-timeandweather": 1.2.2, installed 1.2.2
Adapter    "vw-connect"   : 0.0.72   , installed 0.0.72
Adapter    "web"          : 6.0.3    , installed 5.5.3  [Updatable]
Adapter    "wled"         : 0.7.0    , installed 0.7.0
Adapter    "ws"           : 2.4.0    , installed 2.4.0
Adapter    "zigbee"       : 1.8.18   , installed 1.8.18`

**Comment by klein0r** [comment]
> Ich bin mir nicht ganz sicher, aber ich glaube seit dem stehen unter Histors Zwei Zeilen mit + Zeichen.

Auf deinem Screenshot sind aber keine Zeilen zu erkennen? Das + ist ja nur dafür da, um neue Einträge anzulegen.

**Comment by JBSullivan** [comment]
Wie gesagt, ich weiß es nicht genau, ob dort schon immer zwei + Zeichen untereinander waren, oder ob das erst nach meinen Versuchen im History Bereich so stehen geblieben ist.

Ich habe oben im übrigen noch was hinzu gefügt - vielleicht hilft das ja weiter

**Comment by klein0r** [comment]
> Ich kann dir nicht sagen, welche meiner Adapter diese json Componente verwenden.

Dann wiederhole bitte nicht 10x im Forum und hier, dass mit dem Adapter etwas falsch ist und alles andere läuft 😄 Glaube mir doch einfach, dass das ein Admin-Issue ist (welchen ich bisher nicht reproduzieren kann und nicht weiß wann er auftritt).

Die Frage ist jetzt, was an Deinem System anders ist.

> Ist mit `getHistory` der History Adapter gemeint oder alle Adapter die ein Tracking von historischen Daten, z.B. auf Basis von influxDB zulassen?

Genau, alle Adapter, welche historische Daten aufzeichnen können. Also history, sql und influxdb. Hast Du einen davon installiert? Oder sogar mehrere? Wieviele Instanzen haben die Adapter bei Dir jeweils?

*Das ist aber momentan auch nur eine Vermutung. Wie gesagt, ich kann das alles nicht reproduzieren.*

**Kannst Du in einer komplett leeren Instanz von `awtrix-light` denn eine neue app anlegen, oder schmiert dann auch die GUI direkt ab?**

> Ich habe eben mal die Adapter Einstellungen als json exportiert. Es ist erstaunlich, wie unterscheidlich die Einstellungen abgespeichert werden, obwohl alle eigentlich nach dem gleichen Schema angelegt wurden.

Das ist okay sieht alles richtig aus.

> Wie gesagt, ich weiß es nicht genau, ob dort schon immer zwei + Zeichen untereinander waren

Ja, waren es schon immer. Kann man drüber sprechen ob das sinnig ist. Aber ist völlig irrelevant für das Thema hier.

**Comment by JBSullivan** [comment]
> Dann wiederhole bitte nicht 10x im Forum und hier, dass mit dem Adapter etwas falsch ist und alles andere läuft

Keine Sorge, ich werde dich nicht weiter mit meinen Beobachtungen belästigen ....... Das Ding ist ja nicht Kriegs entscheidend, sondern nur Nice to Have und wenn es mir zu sehr auf den Sack geht, landet es in der Bucht. Mit meinem DOT Matrix Display bekomme ich die gleichen Infos sowieso schneller, weil es eine lange einzeilige Anzeige hat, wo ich die Information nicht auf zwei "Bilder" splitten muss.  

Das Ulanzi ist halt nur schön bunt und liefert noch ein paar Icons und ich kann es überall mit hin nehmen - ob davon die Welt untergeht, wenn ich es nicht mehr habe - definitiv  NEIN.

Ich bin damit raus..........

**Comment by klein0r** [comment]
> Keine Sorge, ich werde dich nicht weiter mit meinen Beobachtungen belästigen

Meine Bitte war lediglich, dass Du nicht mehrfach wiederholst, was ich schon ausführlich begründet habe. Wie Du siehst, gebe ich mir hier, auf YouTube und im Forum alle Mühe, einen möglichst perfekten Adapter abzuliefern und widme dem Thema sehr viel meiner Freizeit.

Und dann ist es schade, wenn ich sehr konkrete Frage stelle und diese unbeantwortet bleiben.
