### ISSUE TITLE
Some apps are not refreshing after object changed

### ISSUE THREAD

**Issue by Matzebhv** [klein0r/ioBroker.awtrix-light#48]
### The problem

Moin,
ich habe für den PV-Ertrag eine benutzerdefinierte App über den Modbus-Adapter aktiviert.
Diese App verschwindet regelmäßig auf der Uhr, nach einem Adapter Neustart läuft es wieder eine Weile.
Da der Modbus-Adapter nachts hier deaktiviert ist hatte ich erst diesen Umstand in Verdacht. Allerdings liegt es anscheinend nicht daran, ich starte Morgens den Awtrix-Adapter neu, die Anzeige ist da. Nach Feierabend ist die Anzeige dann verschwunden obwohl der Modbus-Adapter noch valide Werte liefert.
Alle anderen Apps funktionieren ohne Probleme.
Gruß
Matthias

![awtrix](https://github.com/klein0r/ioBroker.awtrix-light/assets/20025244/256ae123-50db-4605-bfa6-401d0fbe5453)

### Version of nodejs

18.17.0

### Version of ioBroker js-controller

 5.0.8

### Version of Adapter

0.51

### Operating system running ioBroker

Debian Bookworm

### Checklist of files to include below

- [ ] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Log?

**Comment by Matzebhv** [comment]
> Log?

Moin Matthias,
welchen Loglevel soll ich denn mal mitnehmen? In Debug läuft das Log ja komplett Amok und da ich keine Ahnung habe wann das Problem auftritt könnten recht viele Daten anfallen.

**Comment by klein0r** [comment]
Richtig, aber wie soll ich dann helfen, wenn ich nicht sehe was passiert?

**Comment by klostopfer** [comment]
Hallo zusammen,
habe das gleiche Problem und logge deshalb schon seit ein paar Tagen auf "debug"-Level mit, hab aber leider nach dem letzten Update des js-controllers vergessen das loglevel wieder auf "debug" zu stellen. Jetzt als der Fehler aufgetreten ist, hatte ich somit kein passendes Log. Hab gerade wieder umgestellt und logge wieder mit bis der Fehler wieder auftritt (bei mir dauert das aber normal 2-5 Tage). Trotzdem habe ich jetzt gerade im Log schon mal folgende Zeile gefunden:

`[onStateChange] ignoring customApps state change of "shelly.0.SHSW-PM#xxxxxxxxxxxx#1.Relay0.Power" to 113.37 - refreshes too fast (within 3 seconds) - Last update:`

Der Datenpunkt aktualisiert frühestens nach 30 Sekunden, aber es scheint ja auch die Variable für die letzte Aktualisierung verloren zu gehen. 

Ich melde mich, sobald ich ein Debug-Log habe, in dem der Fehler auftritt, aber vielleicht hilft das ja schonmal.

Viele Grüße
Martin

P.S. Die Seriennummer vom Shelly habe ich entfernt, hab aber keine Ahnung, ob die kritisch ist. Falls die hilfreich ist, sag bescheid.

**Comment by Matzebhv** [comment]
Ich habe jetzt die letzte Version des Adapter drauf, heute Morgen wurde mein PV-Ertrag angezeigt. Keine Ahnung, ob das Zufall ist. Werde beobachten und berichten.
