### ISSUE TITLE
Missing history app icons

### ISSUE THREAD

**Issue by chmaryniok** [klein0r/ioBroker.awtrix-light#50]
### The problem

Icon von Hstorie Apps werden nicht mehr angezeigt.
In Version 0.2.0 gab es noch Icons für history Apss, nach einem update auf v0.5.1 und einem neustart der Instanz sind diese verschwunden.

### Version of nodejs

v16.19.1

### Version of ioBroker js-controller

v7.0.3

### Version of Adapter

v0.5.1

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [ ] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Screenshot?

**Comment by chmaryniok** [comment]
Wovon genau?

![image](https://github.com/klein0r/ioBroker.awtrix-light/assets/34416242/a5c917f7-5c13-4f94-af75-24340fa933db)
![PXL_20230725_074407705 MP](https://github.com/klein0r/ioBroker.awtrix-light/assets/34416242/40d01fad-db75-4542-81d8-2c147abe5be0)

**Comment by klein0r** [comment]
Ah ich dachte auf der Weboberfläche fehlt das Icon zum konfigurieren.

In dem Fall bräuchte ich (wie Du oben schon angehakt hast), ein Log im Debug-Loglevel.

**Comment by chmaryniok** [comment]
Ok, kann ich heute Abend nachreichen. 
Also Log vom erstellen der History App?

**Comment by klein0r** [comment]
Okay und was genau fehlt da nun? Der Adapter übermittelt scheinbar alles richtig an Awtrix-Light

**Comment by chmaryniok** [comment]
Also wie auf dem Foto zu erkennen fehlt das Icon. Hat sich was an der Diagramm breite verändert, so dass das Icon rausfliegt?
Oder übersehe ich eine einstelltung im Adapter?

**Comment by chmaryniok** [comment]
also: `2023-07-25 16:35:36.523 - debug: awtrix-light.0 (95777) sending "POST" request to "/api/custom?name=akkuhistory" with data: {"color":"#FF0000","background":"#000000","line":[37,45,53,64,63,66,62,61,57,71,86],"autoscale":true,**"icon":4,**"repeat":1,"lifetime":160}`

passt nicht zu den settings:

![image](https://github.com/klein0r/ioBroker.awtrix-light/assets/34416242/e7441238-56ff-4204-a7f1-578e363ae809)
