### ISSUE TITLE
Not possible to save after editing.

### ISSUE THREAD

**Issue by Njdfg** [klein0r/ioBroker.awtrix-light#52]
### The problem

The save buttons are not active when you make some changes on the screen. It is only active when you install a new custom adapter and fille the name and the object.

Changes in older adapters are not possible.

### Version of nodejs

18.17.0

### Version of ioBroker js-controller

5.0.8

### Version of Adapter

0.6.0

### Operating system running ioBroker

Ubuntu

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
> It is only active when you install a new custom adapter and fille the name and the object.

Of course, the name is required!

**Comment by Njdfg** [comment]
Thanks for the fast answer,
ok it is actual no edit funktion. But how can delete adapter? When i delete a adapter with the trash bin symbol the save button is also disabled.
Gruß Frank

**Comment by Njdfg** [comment]
When i play with the http – Time (up / down) then the Save button will be activated…. Scarry 😊

 

Von: Matthias Kleine ***@***.***> 
Gesendet: 27 July 2023 16:38
An: klein0r/ioBroker.awtrix-light ***@***.***>
Cc: Njdfg ***@***.***>; Mention ***@***.***>
Betreff: Re: [klein0r/ioBroker.awtrix-light] Not possible to save after editing. (Issue #52)

 

It is only active when you install a new custom adapter and fille the name and the object.

Of course, the name is required!

**Comment by Njdfg** [comment]
Here some Pictures .
![HttpTimeout2](https://github.com/klein0r/ioBroker.awtrix-light/assets/140725327/cd201407-b232-48e3-8a29-721d8d05e2ca)
![HttpTimeout3](https://github.com/klein0r/ioBroker.awtrix-light/assets/140725327/38242c05-723f-4e75-b985-008925b15eef)
![HttpTimeout4](https://github.com/klein0r/ioBroker.awtrix-light/assets/140725327/546dd859-1c99-4d8f-b2dc-c0bbce6e878b)

**Comment by klein0r** [comment]
I'm not able to reproduce this issue. Can you export your instance settings (and upload the json)?

**Comment by Njdfg** [comment]
Thanks for help, Guys you made a nice Job :-) THX
