### ISSUE TITLE
Enhancement: Set Icon Textcolor (and Duration?) on CustomApps Objects

### ISSUE THREAD

**Issue by chmaryniok** [klein0r/ioBroker.awtrix-light#55]
### The problem

Da es ja mittlerweile die Option gibt das Icon abhängig vom Wert zu definieren wäre meine Frage ob es möglich ist das statt in der Adapterkonfiguration in die Objekte zu übernehmen, damit man dies per (Blockly)Script anpassen kann?

Use Case: 
Ich würde gerne 6 verschiedene Akku Icons verwenden, je nach Status des Akkus (Laden, 100% , >80%, >60%, >40%, 0%)
auch gerne mit einer anderen Textfarbe.
(Anzeige Dauer wäre auch noch super)

Das ganze über die Adapter Konfiguration zu definieren funktioniert nicht so wirklich, da man nur 2 Schwellenwerte hat und der weg über mehrere Custom-Apps die ich bedingt Visible true/false schalte hat nicht so wirklich funktioniert, da die Reihenfolge immer durcheinander geworfen wurde.

### Version of nodejs

16-19-1

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

v0.6.2

### Version of awtrix-light firmware

0.71

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Ich möchte die Möglichkeiten überschaubar halten. Ziel des Adapter ist ja, dass man schnell und einfach neue Anzeigen konfigurieren kann. Eventuell füge ich bald noch "Experten-Apps" ein, welche dann gar keine Konfiguration erlauben. Da vergibt man dann praktisch nur den Namen und kann den Rest über Datenpunkte steuern.

Aber die normalen Apps möchte ich nicht noch weiter aufblähen. Sonst sieht am Ende niemand mehr durch, welches Icon warum angezeigt wird.

**Comment by chmaryniok** [comment]
Ok, schade, für mich wäre es halt logischer wenn es als Objekt hinterlegt ist und nicht "versteckt" in der Adapter-Konfig.
Und wenn die Adapter Konfig einfach die Objekte füllt sollte das auch nachvollziehbar sein. 
(Da finde ich eher, das die Logik (> X < Y ) in den Adapter zu schieben auf Dauer für unübersichtlich)

**Comment by klein0r** [comment]
> Und wenn die Adapter Konfig einfach die Objekte füllt sollte das auch nachvollziehbar sein.

Dann würde bei jedem Adapter-Start der Inhalt wieder überschrieben - das ist doch undurchsichtig. Oder man müsste den Wert auf null setzen / den State löschen wenn man wieder Logik aus der Instanz-Konfiguration haben möchte. Das generiert nur Issues und Fragen...

**Comment by chmaryniok** [comment]
> Dann würde bei jedem Adapter-Start der Inhalt wieder überschrieben - das ist doch undurchsichtig. 
Das wäre das erwartete verhalten von Objeken in Adaptern. Zumindest aus meiner Sicht.
Anyway, du darfst dich mit issues und Fragen rumschlagen, daher akzeptiere ich deine Struktur und Idee dahinter :)

**Comment by klein0r** [comment]
> du darfst dich mit issues und Fragen rumschlagen

Genau, und das überfordert jetzt schon viele 😄
