### ISSUE TITLE
Unable to update custom app - "ErrorParsingJson"

### ISSUE THREAD

**Issue by baetzmr** [klein0r/ioBroker.awtrix-light#57]
### The problem

After short time running the instance i get many warnings from awtrix-light: 

warn: (custom?name=pvpower) Unable to update custom app "pvpower": AxiosError: Request failed with status code 500

warn: received 500 response from /api/custom?name=pvpower with content: "ErrorParsingJson"

Restarting the instance helps for a while, then warings return 

### Version of nodejs

v16.20.1

### Version of ioBroker js-controller

5.0.9

### Version of Adapter

0.7.0

### Version of awtrix-light firmware

0.72

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by baetzmr** [comment]
Sorry for late reply. 
Version of adapter is now 0.7.1 with firmware 0.73

Maybe you can see some issues inside the log. 

[awtrix-light.log.txt](https://github.com/klein0r/ioBroker.awtrix-light/files/12318669/awtrix-light.log.txt)

**Comment by klein0r** [comment]
Strange - this works:

```
2023-08-11 07:08:47.523 - debug: awtrix-light.0 (22401) sending "POST" request to "/api/custom?name=pvpower" with data: {"text":"125 W","textCase":2,"background":"#000000","color":"#faf303","icon":"44625"}
2023-08-11 07:08:47.633 - debug: awtrix-light.0 (22401) received 200 response from "/api/custom?name=pvpower" with content: "OK"
```

But this leads to an error:

```
2023-08-11 07:09:07.516 - debug: awtrix-light.0 (22401) sending "POST" request to "/api/custom?name=pvpower" with data: {"text":"128 W","textCase":2,"background":"#000000","color":"#faf303","icon":"44625"}
2023-08-11 07:09:07.583 - warn: awtrix-light.0 (22401) received 500 response from /api/custom?name=pvpower with content: "ErrorParsingJson"
```

- `{"text":"125 W","textCase":2,"background":"#000000","color":"#faf303","icon":"44625"}` - OK
- `{"text":"128 W","textCase":2,"background":"#000000","color":"#faf303","icon":"44625"}` - ERROR

I don't see the problem.

**Comment by baetzmr** [comment]
Habe eine RAM Aufzeichung gemacht. Ich weiß zwar noch nicht genau wieviel der RAM belegt sein darf aber es sind immer so um die 67kb. Ein paar "Ausreißer" nach unten sind drin aber eher unauffällig. Nach Reboot Sind es ca. 110kb und nach Instanz Neustart im iOBroker 98kb. Danach fällt der Wert auf 67kb und pendelt sich dort ein.

![awtrix_free_ram](https://github.com/klein0r/ioBroker.awtrix-light/assets/81546284/64d0e0e4-c01d-4739-9828-22a24a4c87e9)

![log](https://github.com/klein0r/ioBroker.awtrix-light/assets/81546284/207bae1e-3a0e-4515-8743-0440e60b2328)

**Comment by baetzmr** [comment]
Kleiner Nachtrag... Sobald ich eine Custom App entferne (von 8 auf 7 und dann auf 6) steigt auch logischer Weise der freie RAM Speicher an. In dem Fall gibt es  auch keine Warnmeldungen mehr. Sobald ich die App wieder aktiviere gehen die Warnmeldungen prompt wieder los. Scheint also quasi doch etwas mit dem freien Speicher zu tun zu haben. 

![log_6_7_apps](https://github.com/klein0r/ioBroker.awtrix-light/assets/81546284/cf2e6691-514d-459f-bd2b-df0a2c054d6b)

Ich werde mal mit 7 Apps weiter beobachten ob es dann ohne Warnungen geht.

**Comment by klein0r** [comment]
Also mit 7 Apps läuft es noch, aber mit 8 Apps nicht?

**Comment by baetzmr** [comment]
Habe noch mal reduziert auf 6 Apps und hier läuft alles stabil ohne Warnungen. Mit 7 Apps kommen die Warnungen sporadisch.

**Comment by baetzmr** [comment]
0.75 geht leider noch schlechter. Nach dem flashen und starten der iobroker Instanz geht der RAM runter 53kb und dann ging nichts mehr. Werte konnten nicht mehr geupdated werden und das Web Interface war nicht mehr erreichbar. Es half nur noch ein Reboot am Gerät selbst. 

Die Custom FW Firmware.bin (0.73) läuft bei mir problemlos mit mittlerweile 12 Apps

**Comment by klein0r** [comment]
Bitte mit [0.77](https://github.com/Blueforcer/awtrix-light/releases/tag/0.77) testen

**Comment by klein0r** [comment]
Perfekt - ich mache hier mal zu, weil das mit dem Adapter ja nicht so viel zu tun hat. Ich nutze ja einfach nur die API und sende (wie es aussieht) immer gültige JSON Payloads.

Siehe https://github.com/Blueforcer/awtrix-light/issues/261
