### ISSUE TITLE
Hintergrundeffekte funktionieren nur mit Text 

### ISSUE THREAD

**Issue by niiccooo1** [klein0r/ioBroker.awtrix-light#58]
### The problem

Die Hintergrundeffekte lassen sich nur anwenden, wenn im Feld Text etwas steht. Ohne Text lässt sich die Instanz zwar abspeichern, Awtrix überspringt jedoch diese custom App.

Mein Workaround ist im Feld Text ein Punkt einzutragen und die Textfarbe schwarz zu hinterlegen (klappt bei den LookingEyes super, bei den Effekten mit Farbe semi da immer ein schwarzer Punkt zu sehen ist)

### Version of nodejs

v18.16.0

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.7.1

### Version of awtrix-light firmware

0.73

### Operating system running ioBroker

Linux-Docker

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
> Ohne Text lässt sich die Instanz zwar abspeichern, Awtrix überspringt jedoch diese custom App.

Richtig, warum sollte man Apps ohne Inhalt bauen können?

**Comment by niiccooo1** [comment]
In diesem Fall um die Hintergrundeffekte auch ohne Texte zu nutzen. Einfach als Gag zwischen den Apps ein paar Augen zeigen zu lassen oder einer Partie Pong zu zuschauen :)

**Comment by Blueforcer** [comment]
Nutzen in der Tat einige:
https://flows.blueforcer.de/flow/9dZKg529OyE2
