### ISSUE TITLE
[Feature Request] App Transition

### ISSUE THREAD

**Issue by chmaryniok** [klein0r/ioBroker.awtrix-light#59]
### The problem

Seit Version 0.72 gibt es die Option App-Transitions zu definieren.
Wäre Cool das auch im Adapter einstellen zu können.

"[...]adds 9 app-transitions wich can be set via settings API or new HA entity.[...]"

### Version of nodejs

16.19.1

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.7.1

### Version of awtrix-light firmware

0.74

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Was fehlt Dir?

https://github.com/klein0r/ioBroker.awtrix-light/blob/02fda1d6b6354fdb3741f65c18bb14bbe1ac2ad1/README.md?plain=1#L54-L59

**Comment by chmaryniok** [comment]
Damn, sorry ich habe in der Adapter Konfig gesucht und nicht in den Objekten.... ;( 
Zu und weg

**Comment by klein0r** [comment]
> Damn, sorry ich habe in der Adapter Konfig gesucht

Genau da ist es ja auch noch zu finden 😄
