### ISSUE TITLE
Bug report Firmware 0.81 causes wrong icons

### ISSUE THREAD

**Issue by mtoensing** [klein0r/ioBroker.awtrix-light#62]
### The problem

When I use 0.81 awtrix firmware I don't see changing icons within the same app.  I know that > 74 is not supported right now. 

Example: 
Simple app with thresholds for > and < values display the icon 8441-red. It does not matter which value is displayed: 

<img width="1004" alt="Screenshot 2023-08-25 at 14 00 42" src="https://github.com/klein0r/ioBroker.awtrix-light/assets/136737/9cec877c-2a75-4ffc-816d-85b67c848883">

**When I downgrade to .74 it works perfectly.**

### Version of nodejs

recent

### Version of ioBroker js-controller

recent

### Version of Adapter

0.7.1 

### Version of awtrix-light firmware

0.81

### Operating system running ioBroker

Linux, Docker, Synology

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

none

**Comment by klein0r** [comment]
> When I downgrade to .74 it works perfectly.

What should I do?

**Comment by mtoensing** [comment]
Look into this and make sure this is not a problem of the adapter. That's what I would do. I or wait and see.

**Comment by fbnkrs** [comment]
@klein0r 
Do you have plans to support the new firmware version?

There seem to be a few differences, I have not yet had a chance to look into it.

I am sure there are a lot of people that would help, if you need it.

**Comment by klein0r** [comment]
> Do you have plans to support the new firmware version?

What is missing right now? The API hasn't changed (just some details and new features):

https://github.com/Blueforcer/awtrix-light/compare/0.70...0.81#diff-9eddf4dc51bf6a0125ca7fb094468ad284112270385c41cebce4f8f0a29620ab

**Comment by fbnkrs** [comment]
Thx for the clarification.

I was under the impression there were more changes, because I got a second unit yesterday, which had some issues. But I reflashed and now it seems to work with 0.84. 

offtopic: the second one looks less sharp, due to the front glass having a little bit more distance to the matrix panel.


thx again
