### ISSUE TITLE
Apps lassen sich nicht deaktivieren

### ISSUE THREAD

**Issue by nob0dy80** [klein0r/ioBroker.awtrix-light#65]
### The problem

Beim Versuch awtrix-light.0.apps.temp.activate (oder andere Apps) zu deaktivieren/aktivieren, gibt es eine Fehlermeldung.

2023-09-09 15:54:57.735 | warn | Received invalid value for state apps.temp.activate

### Version of nodejs

18.16.1

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.8.0

### Version of awtrix-light firmware

0.86

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Debug log fehlt. Sieht erstmal so aus, als würde der Datenpunkt falsch angesteuert.

**Comment by klein0r** [comment]
https://github.com/klein0r/ioBroker.awtrix-light/blob/5c79169d7496bcf05738330007da7e5adf36d910/docs/de/README.md?plain=1#L140-L143
