### ISSUE TITLE
Feature Request [Indikatoren per Blocky anzeigen]

### ISSUE THREAD

**Issue by Dtrieb** [klein0r/ioBroker.awtrix-light#67]
### The problem

Wäre es möglich das man die Indikatoren per Blocky anzeigen lassen kann?

https://blueforcer.github.io/awtrix-light/#/api?id=colored-indicators

### Version of nodejs

18.12.1

### Version of ioBroker js-controller

 4.0.24

### Version of Adapter

0.8.0

### Version of awtrix-light firmware

0.87

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Geht doch längst

**Comment by Dtrieb** [comment]
> Geht doch längst

Gib mir bitte mal einen Stups in die richtige Richtung, ich sehe es nämlich nicht.

**Comment by klein0r** [comment]
steuere-Block auf den Datenpunkt. Habe ich doch alles lang und breit erklärt:

https://youtu.be/Bn_4ROWFXP4?si=HFqzL7XjaJV5Km3y&t=989
