### ISSUE TITLE
Possibility of negative values in threshold overrides

### ISSUE THREAD

**Issue by derjj2018** [klein0r/ioBroker.awtrix-light#69]
### The problem

Es wäre schön wenn negative Wert bei Schwellenwert-Überschreitungen möglich wären.

### Version of nodejs

16

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.8

### Version of awtrix-light firmware

0.88

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Da gibt es eigentlich keine Limits?
