### ISSUE TITLE
Use a different data point for threshold violations or background effect

### ISSUE THREAD

**Issue by derjj2018** [klein0r/ioBroker.awtrix-light#70]
### The problem

Es wäre schön wenn es möglich wäre einen anderen Datenpunkt für Schwellenwert-Überschreitungen oder Hintergrundeffekt verwenden zu können.

z.B. wenn der aktuell Wert der angezeigt werden soll kleiner als der Wert eines anderen Datenpunkts ist, Farbe ROT.

### Version of nodejs

16

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.8

### Version of awtrix-light firmware

0.88

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Das wird dann aber unglaublich komplex. Mit der nächsten Version füge ich "experten Apps" ein. Diese konfiguriert man dann nicht über die Instanzeinstellungen, sondern komplett über Datenpunkte. Dann muss man das in Scripts eben selbst erledigen.
