### ISSUE TITLE
[JsonConfig] Cannot parse json5 config!

### ISSUE THREAD

**Issue by Grothesk242** [klein0r/ioBroker.awtrix-light#72]
### The problem

Wenn ich in die Einstellungen der Instanz gehen möchte kommt lediglich die Meldung: 

[JsonConfig] Cannot parse json5 config!

Überhaupt ist die config irgendwie schief bei mir. 
Der Adapter versuchte auch mit 

```
2023-09-25 20:29:11.951  - info: awtrix-light.0 (6957) starting. Version 0.8.0 in /opt/iobroker/node_modules/iobroker.awtrix-light, node: v18.18.0, js-controller: 5.0.12
2023-09-25 20:29:12.064  - info: awtrix-light.0 (6957) Starting - connecting to http://192.168.0.111/
2023-09-25 20:29:15.116  - info: awtrix-light.0 (6957) error ECONNABORTED from /api/stats: timeout of 3000ms exceeded
```
Keine Ahnung wo die IP 192.168.0.111 herkommen soll, die gibt es nicht, nicht mal ein Netz 192.168.0.x

Wo kann man die Konfig mal komplett nullen?

### Version of nodejs

18.18.0

### Version of ioBroker js-controller

5.0.12

### Version of Adapter

0.8.0

### Version of awtrix-light firmware

0.88

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

Gogogo

**Comment by klein0r** [comment]
> Wo kann man die Konfig mal komplett nullen?

Was sollte das bringen?

> [JsonConfig] Cannot parse json5 config!

Welche Admin-Version ist im Einsatz?

**Comment by Grothesk242** [comment]
Hat sich erledigt. War eine Kombination aus Netzwerktrouble in meinem Netz und einem Bug im Admin.

**Comment by Grothesk242** [comment]
Closed
