### ISSUE TITLE
when using "App-Einstellungen kopieren von", the property "visible" will not be cloned from "master"

### ISSUE THREAD

**Issue by FraatTailscale** [klein0r/ioBroker.awtrix-light#74]
### The problem

when using "App-Einstellungen kopieren von", the property "visible" will not be cloned from "master".

on the 2nd, 3rd ... all apps will be displayed also when apps property "visible" = false on the master.

### Version of nodejs

18.16.0

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.8.0

### Version of awtrix-light firmware

0.88

### Operating system running ioBroker

debian on nuc proxmox

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Mhhh, yes. Since that settings just copies the **settings** at the moment.

**Comment by klein0r** [comment]
Fixed in 0.15.0
