### ISSUE TITLE
DP TextColor falsches Format

### ISSUE THREAD

**Issue by djmarc75** [klein0r/ioBroker.awtrix-light#8]
### The problem

Der DP TextColor unter Settings

awtrix-light.0.settings.textColor

hat wohl ein falsches Format - liefert bei z.B. #ffffff den Wert 65535 zurück, was ja erstmal korrekt ist aber nicht den HEX anzeigt wie es sein sollte :)

### Version of nodejs

18.16.0

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

0.0.6

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Jau gestern Abend noch gesehen aber noch keine Energie für gehabt 😄 Fehlen ja auch noch einige Settings - ist Fleißarbeit die Objekte alle anzulegen...

**Comment by djmarc75** [comment]
in der Ruhe liegt ja bekanntlich Kraft ;)
