### ISSUE TITLE
Problems getting data from new mobilealerts script

### ISSUE THREAD

**Issue by jevylux** [klein0r/ioBroker.awtrix-light#83]
### The problem

I wanted to try to get data from mobilealerts in awtrix.
The adapter does not seem to work anymore, so i used the new script from  the example.js fromhere : https://github.com/bluerai/ioBroker.mobile-alerts/tree/master/alternative

However the data is not displayed in awtrix.
the original data looks like 
<img width="1599" alt="Pasted Graphic" src="https://github.com/klein0r/ioBroker.awtrix-light/assets/198311/918d7edf-dd3b-4c93-bdc2-a6dacb3c9831">

in the logs is see this messages

[refreshCustomApps] Refreshing custom apps for objId "javascript.0.mobileAlertsScript.0.Devices.126CB6B67037.t1" with data {"type":"number","unit":"°C","ts":1697556332819}

[refreshCustomApps] Refreshing custom app "livingtemp" with icon "46567" and text "Living %s %u"

and there is no post as with working apps.

### Version of nodejs

18.16.0

### Version of ioBroker js-controller

5.0.12

### Version of Adapter

0.8.0

### Version of awtrix-light firmware

0.88

### Operating system running ioBroker

linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
> However the data is not displayed in awtrix.

Looks like the state value is not acknowledged.

https://github.com/klein0r/ioBroker.awtrix-light/blob/2930548e5b85c78decbe32b347d61153c0a55a4e/docs/en/README.md?plain=1#L132
