### ISSUE TITLE
Hidden / Invisible apps reappear after device restart

### ISSUE THREAD

**Issue by fefi-byte** [klein0r/ioBroker.awtrix-light#9]
### The problem

Die Änderungen, wie das ausblenden einiger Apps, werden nicht gespeichert. Nach einem Neustart der Uhr wird alles zurückgesetzt.

### Version of nodejs

16.19

### Version of ioBroker js-controller

3.16

### Version of Adapter

0.0.6

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Das ist aber ein Issue für awtrix light und nicht für den Adapter hier?

**Comment by fefi-byte** [comment]
Dann werde ich mal dort nachfragen.

**Comment by klein0r** [comment]
"Visible" wurde jetzt für alle Apps entfernt: https://github.com/Blueforcer/awtrix-light/issues/178
