### ISSUE TITLE
Custom App Name disables Save-Button(s)

### ISSUE THREAD

**Issue by nobiman** [klein0r/ioBroker.awtrix-light#90]
### The problem

When naming a custom App "humidity", the input field turns red and the "Save" and "Save and exit" buttons are disabled and get a red border, so that saving is no longer possible. Naming "humididy" or "humidyti" and all other variations are working fine.
The problems starts with version 0.9

### Version of nodejs

18.6.1

### Version of ioBroker js-controller

5.0.12

### Version of Adapter

0.10

### Version of awtrix-light firmware

0.90

### Operating system running ioBroker

macOS 14.0

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

This is not really a bug, rather a cosmetic problem. There is also no indication in the log when the problem occurs.
And last, but not least:

Many thanks for this fantastic adapter!

**Comment by nobiman** [comment]
The ioBroker OS is "buanet iobroker docker (official image 0.8.0)", my client is MacOS, Sorry.

**Comment by klein0r** [comment]
Thanks for reporting - the default app names have been changed in a previous version and the documentation wasn't updated

**Comment by nobiman** [comment]
Ah! Okay, thank you for fast response!
