### ISSUE TITLE
Feature Request - Zeitgesteuerte Custom Apps

### ISSUE THREAD

**Issue by tommyMX** [klein0r/ioBroker.awtrix-light#92]
### The problem

Hi, 

es wäre gut wenn man die Apps Zeitsteuern kann die man erstellt hat, also nach Wochentagen und Stunden :-)

Lg
Tom

### Version of nodejs

18.18.2

### Version of ioBroker js-controller

5.0.12

### Version of Adapter

6.12.0

### Version of awtrix-light firmware

0.10

### Operating system running ioBroker

Synology

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Nimm einfach einen Zeitplan, welcher den Visible-Datenpunkt der jeweiligen App ansteuert.
