### ISSUE TITLE
Support of JSON payloads for expert apps

### ISSUE THREAD

**Issue by pancetta** [klein0r/ioBroker.awtrix-light#93]
### The problem

No problem, but a feature request: instead or in addition to providing plain text in the expert app, it would be great if we could provide a JSON payload. I'm doing a status notification on demand using `sendTo`, but it would be awesome if the status message would also appear as a regular (or expert) app. Maybe I'm missing something here and there's a way to do that, but I did not see it (yet). Any help is appreciated. This is an awesome adapter, thanks a lot for this!

### Version of nodejs

16.19.0

### Version of ioBroker js-controller

5.0.12

### Version of Adapter

0.10.0

### Version of awtrix-light firmware

0.90.0

### Operating system running ioBroker

QNAP docker container, v7.2

### Checklist of files to include below

- [ ] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Apps and notifications are two different things?!
