### ISSUE TITLE
Setting Visible State via Blocky doesn't have effect

### ISSUE THREAD

**Issue by dhoffmann1979** [klein0r/ioBroker.awtrix-light#94]
### The problem

If the visible state of an app is set via Blockly Script it doesn't show or hide the app on the Ulanci device. When I change the same object over the admin panel it works without problems.

### Version of nodejs

18.18.0

### Version of ioBroker js-controller

5.0.16

### Version of Adapter

0.10.0

### Version of awtrix-light firmware

0.90

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

[iobroker.current.log](https://github.com/klein0r/ioBroker.awtrix-light/files/13422813/iobroker.current.log)

**Comment by klein0r** [comment]
Dann fehlen Dir wahrscheinlich ein paar Grundlagen zum Thema Blockly? Ich wette, Du nutzt den "aktualisiere" statt den "steuere" Baustein: https://www.youtube.com/watch?v=p5FyeifYUnw

Gerne hier reinschauen, um den ioBroker besser zu verstehen: https://haus-automatisierung.com/iobroker-kurs/

**Comment by dhoffmann1979** [comment]
Da hattest du leider recht :-) und das obwohl ich deinen Kurs fast ganz durch habe....

**Comment by klein0r** [comment]
Perfekt 😄 Dann kreide ich mir das selbst an und werde das Thema bei der erneuten überarbeiteten Variante des Kurses noch stärker hervorheben.
