### ISSUE TITLE
App Text ohne Wert und Einheit nicht mehr speicherbar.

### ISSUE THREAD

**Issue by haahne** [klein0r/ioBroker.awtrix-light#95]
### The problem

Guten Tag,
ist es nicht mehr möglich einen Text in den App's anzugeben ohne Wert und Einheit? 

Ich habe noch alte App's laufen bei denen es Ohne %s und %u geht.  

Wenn ich jetzt eine neue App ohne %s /%u mit einem beliebigen Text speichern möchte bleiben Speichern und Speichern und Schließen ausgegraut. 

### Version of nodejs

18.17.1

### Version of ioBroker js-controller

9.6.7

### Version of Adapter

0.10.0

### Version of awtrix-light firmware

0.90

### Operating system running ioBroker

linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
> Wenn ich jetzt eine neue App ohne %s /%u mit einem beliebigen Text speichern möchte bleiben Speichern und Speichern und Schließen ausgegraut.

Das sollte gehen, nur darf dann keine Objekt-ID ausgewählt sein. Welche Admin-Version ist im Einsatz?

**Comment by haahne** [comment]
Ja kann als gelöst markiert werden. Vielen Dank. 
Ich hab bei Objekt immer "Objekt" eingetragen. 
Super Adapter :) 
Ist es normal das wenn ich etwas in den Text schreibe oder lösche es immer ein wenig dauert bis da was passiert. Ich denke dann immer der Adapter ist abgeschmiert, nach ein paar Sekunden funktioniert dann alles. Ist mir bis jetzt nur bei diesem Adapter aufgefallen bei allen anderen läuft es Smooth.

**Comment by klein0r** [comment]
> Ich hab bei Objekt immer "Objekt" eingetragen.

???

**Comment by klein0r** [comment]
> Ist es normal das wenn ich etwas in den Text schreibe oder lösche es immer ein wenig dauert bis da was passiert.

Das hängt von der Performance deines Clients / Browsers ab. Paar Sekunden dauert es bei mir definitiv nicht. Eher so 100ms
